### ISSUE TITLE
Avro upload cannot disambiguate types

### ISSUE THREAD

**Issue by artktonic** [googleapis/google-cloud-dotnet#11062]
I'm using Avro format to upload data to BQ, but cannot disambiguate between NUMERIC/BIGNUMERIC and DATETIME/TIMESTAMP. Errors are in the form of "Field x has changed type from DATETIME to TIMESTAMP" or "Field x has changed type from BIGNUMERIC(40,2) to NUMERIC". I'm using BigQueryClient.UploadAvroAsync(). I have *no* control over the table schema. We cannot use CSV because the schema also includes arrays and may include STRUCT in the future. Avro is preferred over JSON because we're moving very large amounts of data and, even with compression, JSON isn't as efficient as Avro.

The issue with BIGNUMERIC/NUMERIC could be *partially* mitigated by setting DecimalDataTypes to ["NUMERIC", "BIGNUMERIC"] in the JobConfigurationLoad object but that is not accessible (UploadDataAsync() is private) and the UploadAvroOptions doesn't support that parameter, unlike UseAvroLogicalTypes. I say "partially" because it's possible to have a column declared as BIGNUMERIC(5,2); the DecimalDataTypes disambiguation would choose NUMERIC because of the precision and scale and would still fail.

There doesn't seem to be any way of dealing with DATETIME and TIMESTAMP.

What would be useful, at least to me, is to have BQ accept a property in the Avro field schema, perhaps 'sqlType'. I see that such a property is used with the JSON type but a trial with the decimal types didn't work.

#### Environment details

Environment: Linux VM running on MacOS 13.5.2 on the M1 chipset
.NET version: 7
Package name and version: Google.Cloud.BigQuery.V2 version 3.4.0 (via NuGet)

#### Steps to reproduce
1. Create a table in BQ with these columns:

- numeric_col: NUMERIC(30,2) NULLABLE
- big_numeric_col: BIGNUMERIC(40,2) NULLABLE
- datetime_col: DATETIME NULLABLE

2. Create an Avro document with the following schema. Note that the document doesn't need any data -- the errors happen before any data is accessed.

{"name":"scalar_types","type":"record","fields":[{"name":"numeric_col","type":[{"type":"bytes","logicalType":"decimal","precision":30,"scale":2},"null"]},{"name":"big_numeric_col","type":[{"type":"bytes","logicalType":"decimal","precision":40,"scale":2},"null"]},{"name":"datetime_col","type":[{"type":"long","logicalType":"timestamp-micros"},"null"]}]}

3. Upload using a program that calls BigQueryClient.UploadAvroAsync()

**Comment by jskeet** [comment]
This sounds like it's really a matter for the BigQuery team, rather than us as the client library maintainers - there's nothing we can do to add to the library if there's not support in the API.
If there's something in the JobConfigurationLoad that you're asking to be exposed in the library, we can definitely do that. For example, we could expose DecimalTargetTypes - but it sounds like that wouldn't actually solve the problem for you really. Please let me know if that would at least be useful, and we can follow up on it. (Another possibility is to provide a more general purpose interception option, so you can "tweak" the JobConfigurationLoad before it's sent in the request.)

If this *is* a feature request for the API, please follow one of the routes on the [BigQuery support page](https://cloud.google.com/bigquery/docs/getting-support) - I suspect that filing a new issue in the issue tracker would be best.

Please let us know how you'd like to proceed.

**Comment by jskeet** [comment]
Okay - we'll see if we can do that in a general way. We've got a few BQ features in progress at the moment, so we'll probably try to release them all together.

**Comment by jskeet** [comment]
Right, you should now (with Google.Cloud.BigQuery.V2 version 3.5.0, being released at the moment) be able to do this using:

```csharp
var options = new UploadAvroOptions
{
    ConfigurationModifier = load => load.DecimalTargetTypes = new[] { "NUMERIC", "BIGNUMERIC" }
};
```

... and then pass those options into `UploadAvroAsync`.

That won't solve the underlying-API-specific aspect, of course, but it's as close as we can get via the client library. I'll close this issue now as we won't be able to do anything more in this repo.
