### ISSUE TITLE
Non-default database in Firestore/Datastore

### ISSUE THREAD

**Issue by ztamas83** [googleapis/google-cloud-dotnet#11145]
I started using the Datastore and Firestore libraries and have problems connecting to a database when the database name is not the default one: "(default)"

As I reckon it is not possible to set the DatabaseId property anywhere as it's internal everywhere. Am I missing something or this is would be a new feature?

**Comment by jskeet** [comment]
For Firestore, this hasn't been publicly exposed yet because the feature is still in preview. When the feature itself goes GA, we'll make the properties public and release a new version of the library.

For Datastore, we have some implementation work to do in order to allow this to be customized. If you want to use it before then, you can always make the "raw" gRPC calls yourself - you'd just be missing out on some of the hand-written code that makes life a bit simpler.

**Comment by jskeet** [comment]
Assigned to @anuragsrivstv as he's planning on working on Firestore.

**Comment by ztamas83** [comment]
Thanks, makes sense if the feature is not GA yet!

**Comment by jskeet** [comment]
Both Firestore and Datastore now have stable libraries including multiple database support.
