### ISSUE TITLE
SpannerConnection.BeginTransaction() doesn't work

### ISSUE THREAD

**Issue by aousee** [googleapis/google-cloud-dotnet#11371]
I was running two instances of Visual Studio and wrote the same transaction logic in both. However, to observe data changes, I used different `UPDATE Account SET Blocked = 3 WHERE Id='*^&ST-0'` statements in each.

**1. First, I ran the code up to a breakpoint, as shown in the image below.**
![image](https://github.com/googleapis/google-cloud-dotnet/assets/78615811/b19af5f4-0ab9-4d41-975f-3818c15cd608)

**2. Then, I executed the entire transaction at once in one of the environments, as depicted in the second image.**
![image](https://github.com/googleapis/google-cloud-dotnet/assets/78615811/3313c0c1-f3f5-41fc-8f79-2a87382d2276)

The result was that there were no cancellations, and surprisingly, in the scenario of the first point, the UPDATE was applied, and dirty reads were even possible.

However, it worked when I applied TransactionScope.

**Comment by jskeet** [comment]
Please post code as text rather than images - it makes it much easier to copy/paste into reproduction code (as well as generally being easier to read).

I *suspect* the problem is just that you haven't assigned the transaction into the commands you've created, but I'll let @amanda-tarafa comment on that.
