### ISSUE TITLE
[Google.Cloud.Logging.NLog] ASP.NET documentaiton is missing

### ISSUE THREAD

**Issue by SeanFeldman** [googleapis/google-cloud-dotnet#11466]
`Google.Cloud.Logging.NLog` [documentation](https://cloud.google.com/dotnet/docs/reference/Google.Cloud.Logging.NLog/latest) shows a console application setup only. Is there an equivalent for ASP.NET project?

**Comment by jskeet** [comment]
A console app is the simplest way of showing a "getting started with NLog and GCP" example, partly because there are so few variations to consider. NLog isn't sufficiently high on our priority list that I want to end up with an example for ASP.NET, an example for ASP.NET Core, an example for a Cloud Function etc. My hope is that if you're using NLog, you basically know how to configure it, so can work out how to do so based on the console example.

(In an ideal world with infinite staffing, yes, we probably would have an example for everything - we're very much not in that world though, I'm afraid.)

**Comment by SeanFeldman** [comment]
That's fair. What could be done is add a link to how to configure NLog with ASP.NET to provide the readers with the next steps. That'd be an acceptable compromise.

**Comment by jskeet** [comment]
We could do that - but then it's another link to keep up-to-date, consider ASP.NET vs ASP.NET Core etc. Fundamentally, I've been assuming that you'd only want to use this adapter because you've *already chosen* NLog, so you'd already know how to use it for your context. There's a real slippery-slope argument: should we also include links to ASP.NET and ASP.NET Core documentation for every API, in case you're new to .NET as well?

There's already a link to https://nlog-project.org/ - it feels like that's the right central link to include, and it's up to the NLog team to provide appropriate documentation for "how to configure NLog for ASP.NET". The only GCP-specific aspects here are "what does our log integration need" and I think that's already covered.

**Comment by SeanFeldman** [comment]
> I've been assuming that you'd only want to use this adapter because you've _already chosen_ NLog, so you'd already know how to use it for your context.

This is where the assumption is breaking down 🙂 
I've joined a project where NLog has been used. The project was moved from another cloud provider to GCP, and I'm new to both.

I can understand the hesitance to provide more than the bare minimum. NLog doesn't do a great job of documenting it, either. The closest I found is a [wiki page](https://github.com/NLog/NLog/wiki/Getting-started-with-ASP.NET-Core-6).
