### ISSUE TITLE
network: insert should use StatusCode.AlreadyExists instead of StatusCode.Aborted on preexisting network

### ISSUE THREAD

**Issue by SKMonkeyWay** [googleapis/google-cloud-dotnet#11718]
Hi,

I am seeing unexpected behavior when trying to create a network which might already exist.

#### Environment details

  - OS: WIN 10
  - .NET version: .NET 6
  - Package name and version: Google.Cloud.Compute.V1 2.13.0

#### Steps to reproduce
call NetworksClient.InsertAsync for an already existing network

#### Expected StatusCode on RpcException
StatusCode.AlreadyExists

#### Actual StatusCode on RpcException
StatusCode.Aborted with need to parse Status.Detail for already exists message

**Comment by jskeet** [comment]
This sounds like it's really a service anomaly rather than a client libraries anomaly - it would be inappropriate for the client libraries to change the status code reported by the service, in my view. It sounds like the client library is accurately representing what the service is returning - please correct me if I'm wrong.

**Comment by SKMonkeyWay** [comment]
Ah right, I didn't think that through..
Thanks for the reply
