### ISSUE TITLE
Code Example for BigQuery Storage Write Api with CDC

### ISSUE THREAD

**Issue by AndiBuzer** [googleapis/google-cloud-dotnet#12576]
At the moment I'm trying to use the Google.Cloud.BigQuery.Storage.V1 Nuget Package to write data into my BigQuery tables. That works fine for the most part, but it got tricky as I'm trying to use the CDC mechanism now and there is almost no information online in how to use the package with cdc.
For example the ali returns "Upsert is not a valid mode in Insert Mode" but what insert mode is and how to switch from it is nowhere to be found.
So it would be pretty helpful if a code example or at least a section in the documentation targeting cdc and how to use it could be added.

**Comment by jskeet** [comment]
Google.Cloud.BigQuery.Storage.V1 is an entirely generated library - I'm afraid the maintainers of this repository don't have any particular expertise with it. (We just generate it from the API description.)

If the [product documentation](https://cloud.google.com/bigquery/docs/storage_overview) doesn't answer your question, please follow one of the [BigQuery support routes](https://cloud.google.com/bigquery/docs/getting-support).

I'll close this issue now, simply because the maintainers of this repo aren't in a good place help you. If you come across documentation or sample code and you're unsure how to write the same code using the .NET client library, or if you *think* you've written equivalent code but it's not working, we can definitely help you with that.
