### ISSUE TITLE
Creating big number of clients cuts dev's machine from internet

### ISSUE THREAD

**Issue by szogun1987** [googleapis/google-cloud-dotnet#13142]
Thanks for stopping by to let us know something could be better!

#### Environment details

  - OS: Windows 
  - .NET version: Core 6.0 & Core 8,0
  - Package name and version: Google.Cloud.PubSub.V1 3.14.0

#### Steps to reproduce

I don't have exact steps. My app first ensures that all needed topics and subscriptions exists. It creates one PublisherServiceApiClient and one SubscriberServiceApiClient per business event handler (around 50 in total).

Then application creates 2 SubscriberClients per Handler (around 100 in total) so app is able to process events in parallel.
Once it is done my machine is not able to make external http requests, nothing works browsers, http clients in app, etc. 
Everything is getting back to work when I kill app.

I do not dispose clients as the does not have Dispose method.
Issue started to occur when I implemented automatic topic and subscription creation. Previously I had shared subscription for all handlers now I have separate ones. Current solution is not yet deployed to the cloud, so I don't know how it behaves there.

Are there any patterns (like pooling) to prevent this issue?

**Comment by jskeet** [comment]
It's *very* strange that it completely kills your internet connection. That shouldn't be able to happen whatever the app does.

One thing I'd suggest is to only create one underlying SubscriberServiceApiClient per SubscriberClient, by setting the ClientCount on the SubscriberClient property. Otherwise you may well be creating 10 or more clients for each subscriber, depending on your machine specification, leading to 1000 separate StreamingPull calls at a time, which I can imagine causing issues.

You could also try adding a dependency on Grpc.Core, and explicitly using the Grpc.Core adapter, as per https://cloud.google.com/dotnet/docs/reference/help/transports - that would change the gRPC implementation you're using.

**Comment by szogun1987** [comment]
First of all: Thank you for quick response.
It may be related to my ISP limitations (like DNS configuration), but, it can be also some issue inside of the library.

This is sample error I receive in another service I execute in parallel to my app:
```
ERROR [.NET TP Worker] Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware - An unhandled exception has occurred while executing the request.
System.Net.Http.HttpRequestException: No such host is known. (skupomat-test.eu.auth0.com:443)
 ---> System.Net.Sockets.SocketException (11001): No such host is known
```
 
I would be more than happy to provide logs/mem-dumps etc. to diagnose it.

**Comment by szogun1987** [comment]
More info:
Issue occurs also if I would change DNS settings to use Google's ones (8.8.8.8, 8.8.4.4) but stops if I use alternative ISP (USB Tethering from my phone).

**Comment by jskeet** [comment]
"No such host is known" suggests that something's stopping DNS from working - if that's a matter of "the application is flooding the network traffic" then that's really a matter of reducing how much network traffic you've got. (Although I'd also say that the OS should possibly be regulating this too.)

Did you try reducing the number of low-level clients per SubscriberClient as I suggested before?

**Comment by szogun1987** [comment]
I've reduced number of SubscriberClient instances by half (by creating single one per business event) and it helped but, number of events is going to grow so it is short term solution.

Are PublisherServiceApiClient and SubscriberServiceApiClient instances Thread safe? I can use shared instances of them used to create infrastructure. If they are thread-safe it would take me 15 mins if not something around hour.

I would buy decent Mikrotik router next week and check if it would help also (currently I used Technicolor one provided by ISP).

As I don't have yet test/stagging environment I would like to understand the issue before I would deploy it to prod.

**Comment by jskeet** [comment]
> I've reduced number of SubscriberClient instances by half (by creating single one per business event) and it helped but, number of events is going to grow so it is short term solution.

I wasn't suggesting changing the number of SubscriberClient instances. I was suggesting a change to the configuration so that each SubscriberClient has fewer underlying SubscriberServiceApiClient instances.

> Are PublisherServiceApiClient and SubscriberServiceApiClient instances Thread safe?

Yes. But I wouldn't expect that to make a difference, in terms of the instances used to create infrastructure. I strongly suspect the real culprits are the SubscriberServiceApiClient instances created by SubscriberClient. The number of underlying clients created depends on the number of cores you've got - but it doesn't (and can't really) take into account how many other SubscriberClient instances you've got.

We don't know how you're creating SubscriberClient instances, but basically I suggest using SubscriberClientBuilder and setting the ClientCount to 1. (For each SubscriberClient.)

**Comment by szogun1987** [comment]
Great it works fine. Previously I was using `SubscriberClient.CreateAsync(subscriptionName);`.

I've just read in the manual that creation of multiple Clients is redundant, As SubscriberClient process multiple messages in parallel on it's own. Thank you for your assistance sir 🫡
