### ISSUE TITLE
TableExistsAsync() Not available in Google.Cloud.BigQuery.V2 and GetTableAsync() throws exception

### ISSUE THREAD

**Issue by travaille-dev** [googleapis/google-cloud-dotnet#14024]
I'm using Google.Cloud.BigQuery.V2 version 3.10.0 nuget package. 

I don't know the intention behind the api, but I'm just trying to validate whether a table already exists in bigquery before I create one. No guidance provided with c# [docs](https://cloud.google.com/bigquery/docs/samples/bigquery-table-exists#bigquery_table_exists-go)

However, it seems odd that if the table doesn't exist, it will throw an exception rather than just returning a null object. 

My current code snippet that does not work
```c#
        //Trying to see if the table already exists in the dataset in case of resets
        var datasetRef = await bqClient.GetDatasetAsync(dataset);
        var tableRef = datasetRef.GetTableReference(tableName);

        var existingTable = await bqClient.GetTableAsync(tableRef);
        if (existingTable is not null)
        {
            _logger.Info("Criteria Table already exists. Will be skipping uploads.");
        }
        else
        {
            //Todo: Create table and populate
        }
```

I could do the following, but it seems bad to be expecting a 404 response and just trusting the 404 to mean "Yes, we have successfully searched your dataset for the provided table and it is not available." Is it your intention for the client to work like this even though the return object of this function is a nullable bigquery table?

```c#
        //Trying to see if the table already exists in the dataset in case of resets
        var datasetRef = await bqClient.GetDatasetAsync(dataset);
        var tableRef = datasetRef.GetTableReference(tableName);
        
        try
        {
            await bqClient.GetTableAsync(tableRef);
            _logger.Info("Criteria Table already exists. Will be skipping uploads.");
        }
        catch (Google.GoogleApiException e) when (e.Error.Code == 404)
        {
            //Table does not exist, so create and populate it.
        }
```

#### Environment details

  - OS: Sonoma 14.6
  - .NET version: 8
  - Package name and version: Google.Cloud.BigQuery.V2 version 3.10.0 

#### Steps to reproduce

  1. Create a dotnet api project
  2. Install Google.Cloud.BigQuery.V2 package

**Comment by amanda-tarafa** [comment]
It is by desing that GetTable will throw if the table does not exist. Calling code should know how to best deal with the exception, whether is truly an error or something can be done about it.

You can continue to do what you are doing, i.e. catching the exception and creating the table there. Alternatively you can attempt to create the table and catch the exception that will be thrown if the table already exists. Here's a list of [BigQuery erros](https://cloud.google.com/bigquery/docs/error-messages) that you can rely upon.

It's unlikely that we add a TableExists method or similar, unless the API itself does so, as we try to mimick the [API surface](https://cloud.google.com/bigquery/docs/reference/rest/v2/tables) as closely as possible.

I'll be closing this issue now as I believe I've addressed your questions, do leave a comment if you believe otherwise.

**Comment by travaille-dev** [comment]
All good to close.

If someone else comes across this and wants to just create the table without checking it's existence first. They can expect a 409 error when they try to create a table that already exists defined at https://cloud.google.com/bigquery/docs/error-messages 
```c#
try
{
  var tableOptions = new CreateTableOptions();
  var createdTable = await bqClient.CreateTableAsync(dataset, tableName, schema, tableOptions);
  // Continue population
}
//Duplicate error defined here https://cloud.google.com/bigquery/docs/error-messages
catch (GoogleApiException ex) when (e.Error.Code == 409)
{
  // Table already created. Nothing to do
}
```
