### ISSUE TITLE
Add better integration tests for Google.Cloud.Diagnostics.AspNet

### ISSUE THREAD

**Issue by iantalarico** [googleapis/google-cloud-dotnet#2167]
Currently it has very few integration tests and should have better coverage.

**Comment by amanda-tarafa** [comment]
Partly addressed in #2294 by adding Error Reporting Asp.Net (self hosted) Web Api integration tests.
Pending Error Reporting Asp.Net MVC integration tests.
Pending all Tracer integration tests.

**Comment by amanda-tarafa** [comment]
Asp.Net Web Api Trace integration tests cannot be written on top of an OWIN hosted Web Apis because the Asp.Net tracer relies heavily on `HttpContext.Current` and `global.asax` events, none of which are available through OWIN. In fact our Tracer won't work for self hosted Asp.Net Web Apis, which might not be a huge problem in itself specially after .Net Core.
So, we still have pending:

- Asp.Net MVC Error Reporting Integration tests

- Asp.Net MVC and Web Api Trace Integration tests

This is blocked by #2297 since we'll need to set up IIS hosted applications for writing the integration tests against.

**Comment by amanda-tarafa** [comment]
Closing this for now as we are reevaluating our Google.Cloud.Diagnostics.* library strategy.
See:

- [Google.Cloud.Diagnostics.AspNet version history](http://googleapis.github.io/google-cloud-dotnet/docs/Google.Cloud.Diagnostics.AspNet/history.html).
- [Google.Cloud.Diagnostics.AspNetCore version history](http://googleapis.github.io/google-cloud-dotnet/docs/Google.Cloud.Diagnostics.AspNetCore/history.html)
