### ISSUE TITLE
Make Google.Cloud.Diagnostics.*.Snippets runable test like other library snippets

### ISSUE THREAD

**Issue by iantalarico** [googleapis/google-cloud-dotnet#2169]

**Comment by amanda-tarafa** [comment]
Partially addressed via #2192. Asp.Net Snippets pending.

**Comment by amanda-tarafa** [comment]
Partially addressed via #2374.
Pending:

- Asp.Net MVC Error Reporting Snippets

- Asp.Net MVC and Web Api Trace Snippets.

**Comment by amanda-tarafa** [comment]
Asp.Net Web Api Trace Snippets cannot be made runnable with OWIN hosted Web Apis because the Asp.Net tracer relies heavily on `HttpContext.Current` and `global.asax` events, none of which are available through OWIN. In fact our Tracer won't work for self hosted Asp.Net Web Apis, which might not be a huge problem in itself specially after .Net Core.
So, we still have pending:

- Asp.Net MVC Error Reporting Snippets

- Asp.Net MVC and Web Api Trace Snippets

This is blocked by #2297 since we'll need to set up IIS hosted applications for making the pending snippets runnable.

**Comment by amanda-tarafa** [comment]
Closing this for now as we are reevaluating our Google.Cloud.Diagnostics.* library strategy.
See:

- [Google.Cloud.Diagnostics.AspNet version history](http://googleapis.github.io/google-cloud-dotnet/docs/Google.Cloud.Diagnostics.AspNet/history.html).
- [Google.Cloud.Diagnostics.AspNetCore version history](http://googleapis.github.io/google-cloud-dotnet/docs/Google.Cloud.Diagnostics.AspNetCore/history.html)
