### ISSUE TITLE
BigQuery - unable to correctly autodetect header for uploaded CSV

### ISSUE THREAD

**Issue by projectzerotohero** [googleapis/google-cloud-dotnet#2574]
## ISSUE:
Unable to correctly autodetect header for CSV that contains "only string" values 

### Notes:
- Same behavior when uploading the CSV in the Web UI.
- If the CSV contains even just a column of int values, it works as expected.

Package version: Google.Cloud.BigQuery.V2 1.3.0-beta05 and Google.Cloud.BigQuery.V2 1.2.0

Here's a sample code:
<pre>
BigQueryJob job = await _client.UploadCsvAsync(datasetId, tableId, null, stream, new UploadCsvOptions
{
     Autodetect = autodetect,
     SkipLeadingRows = 1,
     FieldDelimiter = delimiter,
     WriteDisposition = WriteDisposition.WriteTruncate
});
</pre>

Here is a sample zip file that contains:
- CSV with all strings
- CSV with strings and ints

**[csv_samples.zip](https://github.com/googleapis/google-cloud-dotnet/files/2461737/csv_samples.zip)**

**Comment by jskeet** [comment]
If you get the same behavior uploading the CSV in the web UI, that suggests the problem is server-side rather than an issue with the client library itself. (The maintainers of this repository work with the API teams, but we're not experts in the individual APIs, and won't have the same level of insight about server-side issues as the API teams themselves.)

I'd suggest looking at the [BigQuery support page](https://cloud.google.com/bigquery/support) and choosing a suitable option there - possibly [creating a new issue](https://issuetracker.google.com/issues/new?component=187149&template=0) on the BigQuery-specific issue tracker after [reviewing existing issues](https://issuetracker.google.com/savedsearches/559654).

I suspect that ["Better automatic detection of header when all the columns are string types"](https://issuetracker.google.com/issues/112210765) is an existing issue which would be worth adding a comment to, with the exact behavior you're seeing. (Neither this question nor that issue give details of that behavior, so I can't tell whether they're actually the same or not.)
