### ISSUE TITLE
Request: Vision API Helper Method for PRODUCT_SEARCH

### ISSUE THREAD

**Issue by beccasaurus** [googleapis/google-cloud-dotnet#2677]
Vision service client should have a helper method added for invoking just the `PRODUCT_SEARCH` [`Feature.Type`](https://cloud.google.com/vision/docs/reference/rpc/google.cloud.vision.v1p3beta1#type_1)

See similar previous issues for `OBJECT_LOCALIZATION`:
 - PHP https://github.com/googleapis/google-cloud-php/issues/1303
 - Go https://github.com/GoogleCloudPlatform/google-cloud-go/issues/1160
 - Ruby https://github.com/googleapis/google-cloud-ruby/issues/2482
 - C# (diff) https://github.com/googleapis/google-cloud-dotnet/commit/367420a1602950bdf3271294ffec873c2b76d114
 - Node.js _(these methods are added dynamically, no manual change)_
 - Python _(these methods are added dynamically, no manual change)_
 - Java _(no helper methods afaik)_

/cc @jskeet

**Comment by beccasaurus** [comment]
Related issues for `PRODUCT_SEARCH`:
 - PHP https://github.com/googleapis/google-cloud-php/issues/1412
 - Go https://github.com/GoogleCloudPlatform/google-cloud-go/issues/1214
 - Ruby https://github.com/googleapis/google-cloud-ruby/issues/2593
 - C# https://github.com/googleapis/google-cloud-dotnet/issues/2677

**Comment by jskeet** [comment]
We could do with more information on this:

- Does product search *always* require a ProductSearchParams in order to be useful?
- Are any of the other ImageContext fields useful in product search? (I'm trying to work out what the signature should look like - whether it should just take an ImageContext, or a ProductSearchParams)
- Are there test images and requests we could use for snippets and integration tests?

**Comment by jskeet** [comment]
Implemented in #2688.
