### ISSUE TITLE
FileNotFoundException with Google.Cloud.Speech.V1 while using with .Net core 2.0 target for Unity Game

### ISSUE THREAD

**Issue by ishwara-bhat** [googleapis/google-cloud-dotnet#2767]
I am getting fileload exception for Google.Cloud.Speech.V1
FileNotFoundException: Could not load file or assembly 'Google.Cloud.Speech.V1, Version=1.1.0.0, Culture=neutral, PublicKeyToken=185c282632e132a0' or one of its dependencies.

 I searched for package dependencies online and installed the same.

I use Unity 2018 game environment. I created a dll plugin using Visual Studio 2017. Framework version 4.x. Compatibility .Net core 2.0. 
Inside the DLL project I have imported 
Google.Cloud.Speech.V1 (Tried all version 1.0.1, 1.1.0 beta)

After going through NuGet dependencies, installed 
Grpc.Core
Google.LongRunning
Google.Api.Gax.Grpc

I later added 
Google.Cloud.Iam.V1
Google.Clould.Storage.V1
Google.Protobuf (Just in case any tensorflow format involved )

But when I run the unity game which loads my DLL, it runs into this error "Could not load file or assemble 'Google.Cloud.Speech.V1" 
FileNotFoundException: Could not load file or assembly 'Google.Cloud.Speech.V1, Version=1.1.0.0, Culture=neutral, PublicKeyToken=185c282632e132a0' or one of its dependencies.

Please let me know if any solution for it.

**Comment by jskeet** [comment]
It sounds like this is probably an assembly binding redirect issue, but fundamentally we don't support Unity, I'm afraid.
While some of the REST-based APIs *may* work (e.g. Google.Cloud.Storage.V1) with some effort, the gRPC-based APIs are much more complicated to enable due to the native code involved.

While we would *like* the APIs to work in Unity, I'm afraid it's very unlikely that that will happen in the short or medium term.
