### ISSUE TITLE
firestore: remove `databaseId` option

### ISSUE THREAD

**Issue by jeanbza** [googleapis/google-cloud-dotnet#2803]
Per the internal email thread "Re: nodejs-firestore: Update to v1 API (PR 516)", we should remove the string databaseId = null parameter in [Firestore.Create](http://googleapis.github.io/google-cloud-dotnet/docs/Google.Cloud.Firestore/api/Google.Cloud.Firestore.FirestoreDb.html#Google_Cloud_Firestore_FirestoreDb_Create_System_String_System_String_Google_Cloud_Firestore_V1Beta1_FirestoreClient_).

Rationale: The server API does not currently support this, and there is no immediate plan to do so. If we need it in the future, we can add it wholesale across all languages.

**Comment by jskeet** [comment]
Note to self: let's keep the functionality internally, and just restrict how we expose it.

**Comment by dferretti** [comment]
@jskeet 👋 I just saw the recent [announcement](https://cloud.google.com/blog/products/databases/manage-multiple-firestore-databases-in-a-project). Any chance this DatabaseId can be made public on `FirestoreDb` and `FirestoreDbBuilder`?

**Comment by jskeet** [comment]
@dferretti: It's still in preview, and we don't include preview functionality in our GA libraries. Also, we're just about frozen now in terms of releases before Cloud Next, so it wouldn't be released for a week or so anyway.
When Cloud Next is over, we'll ask the Firestore team about the release schedule: if the feature is going GA soon anyway, we'll probably wait for that; otherwise, we could release a beta version that includes it.
