### ISSUE TITLE
please remove [Where T: class] constraint for ConvertTo<> function

### ISSUE THREAD

**Issue by alexdoan102** [googleapis/google-cloud-dotnet#2843]
Please remove the please remove [Where T: class] constraint for ConvertTo<> function. It is causing downstream issues, with calling this function (within generic methods that do not have this constraint)

Please change the function to:

      public T ConvertTo<T>() 
        {
            if (!Exists)
            {
                return default(T);
            }
            return (T) ValueDeserializer.DeserializeMap(Database, Document.Fields, typeof(T));
        }

=========================================================

NOTE:  I removed the [Where T: class] , and changed to return default(T)
 ==> you only need the T: class constraint, becuase you wanted to return null.
   ==> but your valueserializer works any T, so there is no need for this constraint.

Default(T) will return null if T is class.

**Comment by jskeet** [comment]
I'm somewhat in two minds about this.

The constraint is intentional, in that we don't support convert documents to value types - and if you try for a non-existent document and end up with a valid value (e.g. 0) that's not ideal by any means.
On the other hand, I do see how it's annoying.

The situation becomes more complex with C# 8:

- With the constraint, we can make the return type `T?` which would correctly express the intent
- Without the constraint, the method signature would effectively express that the return type is non-nullable when T is non-nullable, despite us returning a null value.

I'm currently minded to make the requested change, but with a bunch of extra unit tests to document the behaviour. I'm asking internally to see how this affects anything else.
I'd suggest closing #2844, and once I've decided on a course of action I can implement it with the extra tests. This also means we don't need to work out why the CLA signing isn't working.

**Comment by alexdoan102** [comment]
thanks much. I Per your request, I have closed 2844.

**Comment by alexdoan102** [comment]
this works now in version 1.0.0-beta19.  You are awesome. thx!
