### ISSUE TITLE
Speaker Diarization - Speaker Tag in C#

### ISSUE THREAD

**Issue by SanaWaseem** [googleapis/google-cloud-dotnet#2856]
I know, speakerDiarization is not being advertised for C#, but i really need to implement it. Can you guys please guide me how to get the speakerTag in the response object ? I have been successfully been able to use the beta nuget package, but am clueless about speakerTag, Thanks

**Comment by jskeet** [comment]
I'm not sure which package you're using - you need to use `Google.Cloud.Speech.V1P1Beta1`. There's then a `WordInfo.SpeakerTag` property.

**Comment by SanaWaseem** [comment]
I am using Google.Cloud.Speech.V1P1Beta1 version 1.0. There is no such property

**Comment by jskeet** [comment]
Yes, because it looks like your account has problems again, and I can't help you with that. I suggest you contact the regular support lines to find out what's going on with your account and why it won't allow you to authenticate. I will close this issue now as I believe the specific question has been answered.

**Comment by SanaWaseem** [comment]
{{ "alternatives": [ { "transcript": "good morning Law Offices homemade Rector call a good morning is Mr Brown available", "confidence": 0.7976806 } ], "languageCode": "en-us" }} -> this is the response I am getting, there is no words in alternative object.

**Comment by SanaWaseem** [comment]
From the code that you have provided, the response always returns 0 as the speaker tag, No matter how many speakers are there in the audio. Is this an issue ? 
Below is the code im using:

 ```
var longOperation = speech.LongRunningRecognize(new RecognitionConfig()
                {
                    Encoding = RecognitionConfig.Types.AudioEncoding.Linear16,
                    DiarizationSpeakerCount = 2,
                    EnableSpeakerDiarization = true,
                    SampleRateHertz = 16000,
                    LanguageCode = "en",
                }, RecognitionAudio.FromFile("testRecording.wav"));

                longOperation = longOperation.PollUntilCompleted();
                var response = longOperation.Result;
                Console.WriteLine("Response received successfully.");

                foreach (var result in response.Results)
                {
                    foreach (var alternative in result.Alternatives)
                    {
                        foreach (var word in alternative.Words)
                        {
                            Console.WriteLine($"{word.Word}: {word.SpeakerTag}");
                        }
                    }
                }
```

**Comment by SanaWaseem** [comment]
One more thing that i noticed is it works fine for short audios.

**Comment by jskeet** [comment]
I'm afraid this isn't something I'd know about - it's about the API itself rather than the library access to it. I suggest you ask on the [Google Group for the API](https://groups.google.com/forum/#!forum/cloud-speech-discuss) which is more likely to include the engineers who work on the server-side implementation.
