### ISSUE TITLE
Set / update object custom metadata on Cloud Storage

### ISSUE THREAD

**Issue by lluismontero** [googleapis/google-cloud-dotnet#2901]
Hi,

I've reviewed both the documentation and the SDK source code but haven't been able to find any way to set or update object custom metadata.

The class "Google.Apis.Storage.v1.Data.Object" has a "Metadata" field (List<String, String>) but there is no way to fill this information (add custom fields) with the provided SDK methods. I've only seen an "ExtraMetadata" on the "Google.Cloud.Storage.V1.CopyObjectOptions" that seems a field to add new information when copping an object but I don't think it is the correct option for just add metadata to an object (I don't want to make a copy of it).

It would be very useful to add a "Metadata" (List<String, String> field to the "Google.Cloud.Storage.V1.UploadObjectOptions" / "Google.Cloud.Storage.V1.UpdateObjectOptions" classes or update the "Google.Cloud.Storage.V1.PatchObjectOptions" with a new property for custom fields or, if not possible, add a new method to do it with the "StorageClient".

**Comment by jskeet** [comment]
I don't quite follow, I'm afraid. It doesn't need to be part of `UpdateObjectOptions` or `PatchObjectOptions` because both `UpdateObject` and `PatchObject` already accept a `Google.Apis.Storage.v1.Data.Object` - you can populate the `Metadata` property on the object that you pass in.

I have an [example in my NodaTime project](https://github.com/nodatime/nodatime/blob/master/build/HashStorageFiles/Program.cs) where I use metadata to keep a SHA-256 hash.

**Comment by lluismontero** [comment]
Ok, haven't tried that. Cool thanks!
