### ISSUE TITLE
Multiple 'INTERLEAVE IN PARENT' in one table

### ISSUE THREAD

**Issue by laljikanjareeya** [googleapis/google-cloud-dotnet#2995]
Hi,

I have three tables Departments, Cities and Students.

Now I want to give the relationship (using INTERLEAVE IN PARENT) of the Departments and Cities in Students table I did below Code, however, while creating Student table it throws Exception of "InvalidArgument".

Is it possible to define more than one interleaved in one table?

Here is Sample Code:
```javascript
using (SpannerConnection connection = new SpannerConnection(connectionString))
                {
                    SpannerCommand createTableCmd = connection.CreateDdlCommand(
                                @"CREATE TABLE Departments (
                                Id    INT64 NOT NULL,
                                Name  STRING(50),
                              ) PRIMARY KEY (Id)");
                    await createTableCmd.ExecuteNonQueryAsync();

                    createTableCmd = connection.CreateDdlCommand(
                                @"CREATE TABLE Cities (
                                Id    INT64 NOT NULL,
                                Name  STRING(50),
                              ) PRIMARY KEY (Id)");
                    await createTableCmd.ExecuteNonQueryAsync();

                    createTableCmd = connection.CreateDdlCommand(
                         @"CREATE TABLE Students (
                                Id         INT64 NOT NULL,
                                FirstName  STRING(50),
                                LastName   STRING(50),
                                DepartmentId   INT64,
                                CityId INT64
                              ) PRIMARY KEY (Id,DepartmentId,CityId),
                                INTERLEAVE IN PARENT Departments, INTERLEAVE IN PARENT Cities");
                    await createTableCmd.ExecuteNonQueryAsync();
                }
```
Let me know if more detail required.

**Comment by jskeet** [comment]
I don't believe this is supported, no. I know nothing about interleaved tables, but looking at the grammar in the [DDL documentation](https://cloud.google.com/spanner/docs/data-definition-language) it only shows a single `cluster` option, rather than it being repeated.

This isn't really to do with the .NET client library - you'll see the same error in the Spanner console if you try to create the table there. I'm going to close this issue as issues in this repo are really intended for problems/features related to the .NET client library. I suggest you have a look at the options on the [Spanner support page](https://cloud.google.com/spanner/docs/getting-support) if you want to make this a feature request for the Spanner team. (The maintainers of this repo work on client libraries across APIs, but aren't directly in the teams producing the APIs themselves.)
