### ISSUE TITLE
Firestore SDK think a number is integer instead of double

### ISSUE THREAD

**Issue by wikes82** [googleapis/google-cloud-dotnet#3013]
Getting "Unable to convert integer value to System.Double" on ConverterBase.cs :line 94

#### Steps to reproduce

1. create a document using firestore C# sdk with Double field
2. modify the field using Google Firestore console or cloud function but set the number to whole number.
3. retrieve the same document using C# sdk.
If you only modify the fields through C# sdk, it will always work, even if you set it as whole number using SDK.

**Comment by jskeet** [comment]
Right, so you've ended up storing an integer instead of a double. If you then try to fetch that as a double value, that will fail.
I suspect if you set it to (say) 5.0 instead of 5 (in Cloud Functions or the console), it will be fine.

If you really need to deserialize both integers and doubles, you can do so - exactly *how* you do that will depend on how you're deserializing. I would strongly recommend keeping the schema the same across all your code though.

**Comment by wikes82** [comment]
I don't see anyway I could save 5.0 on console, if I entered it as 5.0 it always converted into 5. On cloud function I always use parseFloat()

**Comment by jskeet** [comment]
Hmm. That sounds like it's a console / Cloud Functions issue rather than an issue with the C# library then, really. I wouldn't want to change the library to silently accept floating point values as integers or vice versa - instead, I think it's better to be explicit when you're in a situation where you need to do that.

If you let me know how you're fetching this value, I can give some advice on how you can work around it in the C# library, but I don't think we'd want to change our behaviour.

**Comment by wikes82** [comment]
I'm using DocumentSnapshot.ConvertTo<T>() to deserialize the document,
and the C# model something like this : 

[FirestoreProperty("total")]
public double Total { get; set; }

The weird thing is, if I store whole number using C# it works, and even if I view it on console, it looks exactly the same (e.g : 5)

**Comment by jskeet** [comment]
The library uses the CLR type - "5 as a double" and "5 as an int" are different values, just as they are within the Firestore document.

In your model, you could use:

```csharp
public double Total
{
    get => RawTotal.ValueTypeCase == Value.ValueTypeOneofCase.NullValue ? RawTotal.DoubleValue : (double) RawTotal.IntegerValue;
    set => RawTotal = Value.ForDouble(value);
}

[FirestoreProperty("total")]
private Value RawTotal { get; set; } = Value.ForDouble(0.0);
```

I haven't tested that, but I'd *expect* it to work. I would definitely *try* to change the other code that modifies the document, to get that consistent, rather than having to make sure you can handle the inconsistency everywhere.

**Comment by wikes82** [comment]
This is part of my cloud function codes, how do I change it so that it's always generate compatible value with C# ? It's is should already be in Float because of parseFloat()

ticketTotals.paymentTotal = parseFloat(ticketPayment);

if value of ticketPayment is whole number, it will failed deserialized into C#, but if the value is decimal it's good. 
The same Firestore document deseriazlied fine on Android Firestore SDK, I really think it's an issue with C# SDK.
The SDK should be able to deserialize number value into the C# declared data type.

**Comment by jskeet** [comment]
I agree that it sounds like it *should* be a float, but it sounds like it really *is* an integer. Bear in mind that deserializing an integer to a floating point value can lose information, which I'd rather not do implicitly. (It's very possible that the Android SDK does that, even so.) I'll ask the Firestore team how they'd expect this to be handled.

**Comment by jskeet** [comment]
While I'm asking internally, I've got a fairly simple option for you - a custom converter that can convert both integer and floating point values to `double`. Here's a complete sample:

```csharp
using Google.Cloud.Firestore;
using System;
using System.Threading.Tasks;

namespace Issue3013
{
    class Program
    {
        static async Task Main(string[] args)
        {
            if (args.Length != 1)
            {
                Console.WriteLine("Please provide the project ID as a command line argument");
                return;
            }

            var db = FirestoreDb.Create(args[0]);
            var doc = db.Collection("Issue3013").Document();

            // Create a value that uses an integer
            await doc.CreateAsync(new { Name = "Test", Value = 10 });

            // But deserialize it to the entity type
            var snapshot = await doc.GetSnapshotAsync();
            var entity = snapshot.ConvertTo<Entity>();
            Console.WriteLine($"{entity.Name}: {entity.Value}");
        }
    }

    [FirestoreData]
    class Entity
    {
        [FirestoreProperty]
        public string Name { get; set; }

        [FirestoreProperty(ConverterType = typeof(IntegerOrDoubleConverter))]
        public double Value { get; set; }
    }

    class IntegerOrDoubleConverter : IFirestoreConverter<double>
    {
        public double FromFirestore(object value) =>
            value is double d ? d
            : value is long integer ? integer
            : throw new ArgumentException("Expected double or integer value");

        public object ToFirestore(double value) => value;
    }
}
```

If you copy that `IntegerOrDoubleConverter` class into your code and change any `double` properties to specify it (e.g. `[FirestoreProperty(ConverterType = typeof(IntegerOrDoubleConverter))]`) then it should work.
*If* we change the library to make that the default behaviour, you'll then be able to remove the converter after updating. (But you wouldn't have to - there shouldn't be any difficult timing issues here, as the converter will still work even after it becomes unnecessary.)

**Comment by wikes82** [comment]
I'm going to use this work around for now.
Thank You so much for your help Jon

**Comment by jskeet** [comment]
@wikes82: My pleasure - thanks for bringing the issue to my attention. I've prepared a PR (#3014) if we *do* want to make this the global case. We're definitely not blocked on technical challenges - it's only a matter of deciding the most desirable behaviour.

**Comment by jskeet** [comment]
The conversion is now in the master branch, and will be picked up in the next release. I won't be releasing today, but could do next week if that would be useful.
