### ISSUE TITLE
Translation adds spaces around some special characters.

### ISSUE THREAD

**Issue by OpenSpacesAndPlaces** [googleapis/google-cloud-dotnet#3126]
Translation adds spaces around some special characters.

Test Case: |7533||||||
Result:  | 7533 ||||||

Why this is a problem:
Creation of placeholders for phrases that should not be translated and usage of an html wrapper is not possible (due to invalid html concerns).

Other reports of this problem:
https://stackoverflow.com/questions/54427119/google-translate-adds-spaces-around-special-characters
https://issuetracker.google.com/issues/119256504

**Comment by OpenSpacesAndPlaces** [comment]
Also noting this doesn't seem to be consistent - "." seems to only do a space after.

Test Case: .1752...............
     Result: .1752 ...............

Also tried adding a normal letter like "Z". 
Sometimes it would add an extra "Z" to the end and sometimes it wouldn't.

Is there any command sequence that the API will leave alone 100% of the time?

**Comment by jskeet** [comment]
Thank you for the issue report. This repository is intended for issues with the .NET client libraries, rather than the Translation service itself - in particular, the Translation team don't monitor this repository.

I strongly suggest you add information to the issue tracker issue instead - having a single issue with lots of information is better than multiple issues spread out across the web.
In particular, I'd encourage you to be precise about what "special characters" means to you. (To many people that would be "any non-ASCII character" but different people will have different interpretations.

I'm going to close this issue now as I don't believe this is an issue with the client library itself. I do appreciate that it's a real problem - just not one that I can help with, and it looks like there's already an issue filed in the right place.

**Comment by OpenSpacesAndPlaces** [comment]
> I strongly suggest you add information to the issue tracker issue instead
> I'm going to close this issue now as I don't believe this is an issue with the client library itself. 
Fair enough.

>  I'd encourage you to be precise about what "special characters" means to you
I'm not even sure it's special characters. Even trying other command sequences with all kinds of characters, it seems manipulate spacing seemingly at random.

Integers seem to be left alone - so a command sequence with leading zeroes became the obvious choice.
Not my favorite as there could be collisions, but will probably be fine for most use cases.
(in-case this helps somebody else).

**Comment by OpenSpacesAndPlaces** [comment]
For future reference - other reports of the problem:
https://github.com/soimort/translate-shell/issues/175
https://webapps.stackexchange.com/questions/120850/google-translate-inserting-extra-spaces-in-original-formulas
https://sourceforge.net/p/omegatplus/feature-requests/28/
https://www.proz.com/forum/wordfast_support/224774-spaces_before_and_after_placeables_how_to_switch_them_off.html

**Comment by OpenSpacesAndPlaces** [comment]
Also noted at:
https://issuetracker.google.com/issues/119256504
