### ISSUE TITLE
Google.Cloud.Datastore.V1 channel creation error under CoreRT

### ISSUE THREAD

**Issue by hhblaze** [googleapis/google-cloud-dotnet#3161]
#### Environment details

  - OS: Windows 10
  - .NET version: CoreRT from .NetCore 2.2
  - Package name and version: Google.Cloud.Datastore.V1 2.1.0

#### Steps to reproduce

  1. Everything works and runs in standard managed environment. Everything compiles in CoreRT. 
But when native (CoreRT) runs it shows following problems at this place:

Code of DataStore initialization:

```
static DatastoreDb gdb;
public static void InitDataStore()
        {
            try
            {

                var credential = Google.Apis.Auth.OAuth2.GoogleCredential.FromJson(GetGCS())
                  .CreateScoped(DatastoreClient.DefaultScopes);

//On the next line (while creating channel) will be thrown exception
                var channel = new Grpc.Core.Channel(DatastoreClient.DefaultEndpoint.ToString(), credential.ToChannelCredentials());

                gdb = DatastoreDb.Create(datastore_projectId, datastore_namespace, DatastoreClient.Create(channel));
```
  Here is a screenshot of the exception:
![image](https://user-images.githubusercontent.com/486781/59851847-e4272600-936d-11e9-8592-0e1e825182bb.png)

**Comment by jskeet** [comment]
It sounds like this is a bug that should be filed in [Grpc.Core](https://github.com/grpc/grpc), given that the problem is within `GrpcEnvironment.GrpcNativeInit`. But fundamentally, we don't support CoreRT at the moment. The gRPC team may well be interested in making it work, which would at least be a pre-requisite for our code working.

I suggest you put together a minimal example (which wouldn't need to use Datastore at all - it only needs to call the Channel constructor) and post it in the gRPC repository.

**Comment by hhblaze** [comment]
ok, thank you!
