### ISSUE TITLE
Google Cloud Speech - Model Improving

### ISSUE THREAD

**Issue by peosgusa** [googleapis/google-cloud-dotnet#3238]
Hello,

I'm testing the Google Cloud Speech for a specific context. For example, If i want to use the recognition for a medical purpose as medical reports, some words does not exists in this context,for example: party,car,business, apartment, street. My question is if has a way to redirect the recognition for a **specific** purpose, filtering these words that not fit in my context and replace for similar words that can be useful.

I'm using Speech StreamingRecognizeRequest with this following RecognitionConfig.

```
Config = new RecognitionConfig()
                        {
                            Encoding =
                            RecognitionConfig.Types.AudioEncoding.Linear16,
                            SampleRateHertz = 16000,
                            LanguageCode = "pt-BR",
                            SpeechContexts = **Words Like { "Diceases", "Medical Diagnosis" }**,
                            ProfanityFilter = true,
                            EnableSpeakerDiarization = true,
                            DiarizationSpeakerCount = 1,
                            Model = "default",
                            UseEnhanced = true,
                            Metadata = new RecognitionMetadata()
                            {
                                InteractionType = RecognitionMetadata.Types.InteractionType.Dictation,
                                MicrophoneDistance = RecognitionMetadata.Types.MicrophoneDistance.Nearfield,
                                OriginalMediaType = RecognitionMetadata.Types.OriginalMediaType.Audio,
                                RecordingDeviceType = RecognitionMetadata.Types.RecordingDeviceType.OtherIndoorDevice,
                                ObfuscatedId = ID,
                                AudioTopic = "Radiology"
                            }
                        }
```

Anyone has a tip that can help me with this?

Thanks in advance,

Peosgu

**Comment by jskeet** [comment]
I don't know of any way to do that - but that's really a question about the core Speech API rather than the .NET Client Libraries. If it can be done in the API, I suspect it's trivial to get it working in .NET :)

The contributors in this repo aren't experts in the specific APIs, so we're unlikely to be able to help you. I'll close this issue, but I'd strongly urge you to follow one of the paths on the [Cloud Speech API support page](https://cloud.google.com/speech-to-text/docs/getting-support)  - the [cloud-speech-discuss group](https://groups.google.com/forum/#!forum/cloud-speech-discuss/join) would probably be my first port of call.
