### ISSUE TITLE
BigQuery: Verify/implement list options for job collection

### ISSUE THREAD

**Issue by shollyman** [googleapis/google-cloud-dotnet#3244]
Filing this as a backlog issue for all the client languages.

It looks like the BigQuery API doesn't really expose the `minCreationTime` / `maxCreationTime` options available in jobs.list via tests.  My understanding is that dotnet exports the discovery types directly so there's no need for special wrapped implementations for invoking options.

Ex: https://github.com/shollyman/google-cloud-dotnet/blob/master/apis/Google.Cloud.BigQuery.V2/Google.Cloud.BigQuery.V2.Tests/ListJobsOptionsTest.cs doesn't include the options.

https://github.com/shollyman/google-cloud-dotnet/blob/master/apis/Google.Cloud.BigQuery.V2/Google.Cloud.BigQuery.V2.IntegrationTests/JobsTest.cs#L57 appears to implement time-based filtration by relying on client-side filtration rather than server side filtration.

**Comment by jskeet** [comment]
I'm not sure what you mean by "expose [...] via tests" - did you mean we don't expose it in the API itself? If so, you're absolutely right - and I assume that's because it didn't exist when I first put together ListJobsOptions. Will take this as a feature request to add those - it shouldn't be hard. We can then use them in tests, of course.
