### ISSUE TITLE
Relative doc URLs hosted on googleapis.github.io domain 404

### ISSUE THREAD

**Issue by darthwalsh** [googleapis/google-cloud-dotnet#3356]
Tried:

[x] Search the issues already opened: https://github.com/googleapis/google-cloud-dotnet/issues
[x] Search Stack Overflow: http://stackoverflow.com/questions/tagged/google-cloud-platform+dotnet

#### Environment details

  - OS: N/A
  - .NET version: N/A
  - Package name and version: master branch

#### Steps to reproduce

If you go to [ClusterManagerClient](https://googleapis.github.io/google-cloud-dotnet/docs/Google.Cloud.Container.V1/api/Google.Cloud.Container.V1.ClusterManagerClient.html) docs, and look for any of the hyperlinked zones (often followed by "in which the"), the [link 404's](https://googleapis.github.io/compute/docs/zones#available), because the zone link is `[zone](/compute/docs/zones#available)` which is relative to googleapis.github.io but the content is at https://cloud.google.com/compute/docs/zones#available

I grepped for relative URLs, and found 349 in master today. 

```none
PS C:\code\google-cloud-dotnet> grep -r --include "*.cs" "\](/" .
./apis/Google.Cloud.Container.V1/Google.Cloud.Container.V1/ClusterManagerClient.cs:        /// [zone](/compute/docs/zones#available) in which the cluster
./apis/Google.Cloud.Container.V1/Google.Cloud.Container.V1/ClusterManagerClient.cs:        /// [zone](/compute/docs/zones#available) in which the cluster
./apis/Google.Cloud.Container.V1/Google.Cloud.Container.V1/ClusterManagerClient.cs:        /// [zone](/compute/docs/zones#available) in which the cluster
./apis/Google.Cloud.Container.V1/Google.Cloud.Container.V1/ClusterManagerClient.cs:        /// [zone](/compute/docs/zones#available) in which the cluster

%SNIP%
```

In order to work on the `googleapis.github.io` domain they all need to be absolute URLs to https://cloud.google.com, like https://cloud.google.com. Grepping for already-existing absolute links, I count 854.

**Comment by jskeet** [comment]
This is unfortunately due to the Markdown in the [protos](https://github.com/googleapis/googleapis).

The Markdown processing in protoc is non-existent - we just copy the comments straight into XML, escaping as necessary. It's only because docfx supports Markdown that there's any Markdown support at all. You'll see the same in all other client libraries, I suspect. Ideally, protoc would have decent Markdown support (both centralized and on a per-language basis) with some way of indicating that the links should be resolved relative to cloud.google.com.

I'll create an internal issue on Monday requesting fully-qualified links instead, but I don't know whether it'll happen.

**Comment by jskeet** [comment]
As part of the fixit, let's see if we could patch the protos during the generation process.
