### ISSUE TITLE
Upgrading  Google.Cloud.Storage.V1 2.4.0-beta04 breaks Google.Cloud.Diagnostics.AspNetCore

### ISSUE THREAD

**Issue by voloda** [googleapis/google-cloud-dotnet#3690]
#### Environment details

  - OS: Docker .NET Core 3.0
  - .NET version: Core 3.0
  - Package name and version: Google.Cloud.Diagnostics.AspNetCore 3.0.0-beta14

#### Steps to reproduce

  1. Install project with following packages
    <PackageReference Include="Google.Cloud.Diagnostics.AspNetCore" Version="3.0.0-beta14" />
    <PackageReference Include="Google.Cloud.Storage.V1" Version="2.4.0-beta04" />
  2. Setup Stack driver logging
  3. Try to write a log entry

Following exception is thrown - apparently caused by breaking change in `Google.Api.Gax.CloudRunPlatformDetails` :

```
Unhandled exception. System.MissingMethodException: Method not found: 'System.String Google.Api.Gax.CloudRunPlatformDetails.get_Location()'. at Google.Api.Gax.Grpc.MonitoredResourceBuilder.FromPlatform(Platform platform) at Google.Api.Gax.Grpc.MonitoredResourceBuilder.FromPlatform() at Google.Cloud.Diagnostics.AspNetCore.LoggerOptions.Create(LogLevel logLevel, String logName, Dictionary`2 labels, MonitoredResource monitoredResource, BufferOptions bufferOptions, RetryOptions retryOptions, TextWriter loggerDiagnosticsOutput) at Rakosnicek.Web.Program.<>c.<CreateWebHostBuilder>b__1_2(HostBuilderContext hostingContext, ILoggingBuilder logging) in
```

**Comment by jskeet** [comment]
Thanks for reporting this. I think this *should* be as simple as releasing a new beta of Google.Cloud.Diagnostics.AspNetCore (and .Common) that targets GAX 2.10.0 instead of GAX 2.10.0-beta02. The fact that the code compiles means it should be fine when we've sorted that dependency out. (The breaking change was from a *beta* of GAX - which is okay in general, in that we haven't broken SemVer - but is a problem in this case as we haven't released a new package with the new dependency.)

Assigning this to Amanda to check and then release on Monday.

**Comment by jskeet** [comment]
(As a workaround until then, downgrading to Google.Cloud.Storage 2.4.0-beta03 make it all work.)

**Comment by amanda-tarafa** [comment]
This has now been released. It's available on nuget [here](https://www.nuget.org/packages/Google.Cloud.Diagnostics.AspNetCore/3.0.0-beta15) (still not indexed at the moment of writing this, which means it won't appear on searches).
Closing now. If you encounter this same issue after upgading to Google.Cloud.Diagnostics.AspNetCore v3.0.0-beta15, please reopen.
