### ISSUE TITLE
Dialogflow - Status(StatusCode=DeadlineExceeded, Detail="Deadline Exceeded")

### ISSUE THREAD

**Issue by ganesh-gawande** [googleapis/google-cloud-dotnet#3780]
I am trying to invoke detect intent method and getting this particular exception. 
When I invoke/run the same code from visual studio on local machine - the code works perfectly fine. 
When I deploy the application on server, then I am getting the above exception.

From visual studio, I have published the application and uploaded all published files using FTP to server's virtual directory

```csharp
string jsonFilePath ="JSON FilePath";
Environment.SetEnvironmentVariable("GOOGLE_APPLICATION_CREDENTIALS", jsonFilePath);
SessionsClient _sessionsClient = SessionsClient.Create();

// Initialize request argument(s)
SessionName _sessionName = new SessionName("ProjectId", conversationModel.RequestMessage.SenderId);
QueryInput queryInput = new QueryInput();
var queryText = new TextInput();
queryText.Text = "Hi";
queryText.LanguageCode = "en-us";
queryInput.Text = queryText;

// Make the request
DetectIntentResponse response = _sessionsClient.DetectIntent(_sessionName, queryInput);
```

I have verified that, the JSON File path is correct. My Program is able to find and read the file. 
I have verified that, the environment variable get set. I have read it and printed it.

**Comment by jskeet** [comment]
Could you give more details about your server environment? I suspect the problem is that your server can't reach the Dialogflow server using gRPC, but it's hard to tell from just this.

Are you able to run console applications on your server? That would make it easier to diagnose what's going on, as we could create a tiny console app that just tried to make a call - to various APIs - and then diagnose what's going on from that. It's typically easier than diagnosing web applications.

**Comment by ganesh-gawande** [comment]
That is shared hosting server with IIS access only. So I can run the web application only on that server. That is Plesk hosting server.

If you want, I can quickly modify the code and give the output to you, if required.

**Comment by jskeet** [comment]
Okay, if you can try using a different API, that would make it clearer whether this is a Dialogflow issue or a general networking issue.

If you could:

- Add a dependency to Google.Cloud.Language.V1 version 1.3.0
- Make sure you've got the [Natural Language API](https://console.cloud.google.com/apis/library/language.googleapis.com) enabled
- Include something like the following code in your project:

```csharp
using Google.Cloud.Language.V1;
using System;

namespace Issue3780
{
    class Program
    {
        static void Main(string[] args)
        {
            var client = LanguageServiceClient.Create();
            var response = client.AnalyzeSyntax(Document.FromPlainText("This is a simple sentence"));
            Console.WriteLine(response);
        }
    }
}
```

So you might want to add an extra controller method that returns the JSON, or add some logging - anything that just shows whether that request has worked or not.

**Comment by ganesh-gawande** [comment]
I am facing some issue while adding payment method to enable Natural language processing API. 
When I my card, the money get debited, but browser shows - error response. I tried with two different cards but not worked. Will try after sometime. 

Meanwhile, any other code, I can try ?

**Comment by jskeet** [comment]
Ah, I assumed you already had a billing account in order to use Dialogflow. You can try the same request without enabling the API - it's just that it will definitely fail. It'll still give us information though, in terms of whether it fails due to DeadlineExceeded or an "API was not enabled" exception.

Note that you still need the environment variable set to point at your service account credentials.

**Comment by ganesh-gawande** [comment]
I have got the following exception - 
Status(StatusCode=PermissionDenied, Detail="Cloud Natural Language API has not been used in project 977497125911 before or it is disabled

**Comment by jskeet** [comment]
Okay, so that suggests it *is* managing to make the gRPC call. I don't know why Dialogflow would fail.

For the Dialogflow call, could you add an extra final argument to the call:

```csharp
CallSettings.FromCallTiming(CallTiming.FromTimeout(TimeSpan.FromMinutes(5)))
```

That should give the call 5 minutes to work - I'd be astonished if that weren't long enough. You'll need to import the `Google.Api.Gax.Grpc` namespace. (This is just for diagnostic purposes - I wouldn't expect you to leave that in permanently.)

If you could add timing to the call so you can see how long it takes before it fails, that would help.

Also, could you give us information about exactly which version of the Google.Cloud.Dialogflow.V2 package you're using?

**Comment by ganesh-gawande** [comment]
Adding the timeout as given by, solved the issue. Now I am getting response from the dialogflow. 

An observation is - when IIS is reset, then for the first request - it took around 2 min to get response. 
Here is print I added before DetectIntent statement and after it. 

24-22-2019 **02:22:58 966**: Sending req to dailogflow: 
24-24-2019 **02:24:32 920**: Response received from Dailogflow: 

After the consecutive calls takes less time to execute. 
24-26-2019 **02:26:23 951**: Sending req to dailogflow: 
24-26-2019 **02:26:24 185**: Response received from Dailogflow:

**Comment by jskeet** [comment]
That's very interesting. Are you able to add timing for the Language API call we tried earlier? I wonder whether it *is* something in the networking, but in a "gets better" way. I'd really like to understand this better.

**Comment by ganesh-gawande** [comment]
Here are the timings for Language API - 

After IIS reset - First request
24-31-2019 **04:31:12 387**: Before sending req
24-32-2019 **04:32:46 575**: Status(StatusCode=PermissionDenied

Second request
24-33-2019 **04:33:17 075**: Before sending req
24-33-2019 **04:33:17 122**: Status(StatusCode=PermissionDenied

**Comment by jskeet** [comment]
It's possible this is related to https://github.com/googleapis/google-api-dotnet-client/issues/1475, where the person who raised the issue did some more research which led them to believe this was about their hosting provider not supporting HTTP/2.0 properly. Are you able to raise this with your hosting company?

**Comment by ganesh-gawande** [comment]
Sure. I will raise this with hosting company once. 

Thank you very much for all your support. I appreciate it. 

I am closing this issue.
