### ISSUE TITLE
PubSub publish BatchSettings are being ignored in v1.1.0, 1.2.0

### ISSUE THREAD

**Issue by sm1ke** [googleapis/google-cloud-dotnet#4097]
Google.Cloud.PubSub.V1 v1.1.0 and 1.2.0-beta01 do not seem to be honoring the `BatchingSettings` as was the case in v1.0.0. Code below for v1.0.0 publishes quickly, but in v.1.1.0 onward takes >20 seconds.

```
// windows 10, .net core 3.0

public async Task Do()
{
	var apiClient = PublisherServiceApiClient.Create();

	TopicName topicName = new TopicName("MY PROJECT", "TEST_1");

	PublisherClient publisher = await PublisherClient.CreateAsync(topicName, null, new PublisherClient.Settings()
	{
		BatchingSettings = new BatchingSettings(1, null, null)
	});

	await apiClient.CreateTopicAsync(topicName);

	while (true)
	{
		var sw = Stopwatch.StartNew();
		await publisher.PublishAsync("test");
		Console.WriteLine(sw.ElapsedMilliseconds);
	}
}

/*
	Google.Cloud.PubSub.V1 (1.0.0)
	>>
	843
	121
	143
	132
	130
	143
	119
	120
	44
	27
	42
	44
	41
	37
	43
	43
	43
	46
	41
	40

	Google.Cloud.PubSub.V1 (1.1.0) (1.2.0-beta01)
	>>
	20676
	20254
	20243
	...
*/
```

Similarly for `byteCountThreshold` and `delayThreshold`.

**Comment by chrisdunelm** [comment]
I'm unable to reproduce your result.
Using exactly the code you've provided I see expected performance on v1.0.0, v1.1.0, and v1.2.0-beta01.
My numbers for all package versions look roughly like: 736, 117, 145, 126, 41, 38, 39, ...
I've tested this on Windows 10 with a console app, targetting netcoreapp3.1, netcoreapp2.1, and net461 - all see the same expected performance.

When I change the batch parameters, the timings change as expected. Which indicates that the batch-settings are being honoured as expected.

If you're still seeing this problem, please can you provide more details about the platform you are testing this on, and which framework you're targeting.

**Comment by sm1ke** [comment]
Thanks very much for spending the time to look into it, and with you confirmation I can see I was overly hasty in assuming it was the batch settings.

So I have tested over various frameworks (netcoreapp3.1, 3.0, 2.1) on Windows 10 (console app), on 2 laptops, 2 networks, 2 GCP projects (though same account), and the results I get are consistent.

* v1.0.0 - immediately < 1s publish times
* v1.1.0/v1.2.0 - first 12 messages take ~20s to send (so 4min total), and then subsequent messages are fast << 1s (apologies I was not patient enough to discover they sped up after a 4 min period before)

If I set `BatchingSettings = new BatchingSettings(100, null, TimeSpan.FromSeconds(30))` then the (first) messages will take 20 + 30s = 50s to send (so as you pointed out def not related to `BatchSettings`).

The call to `client.PublishAsync` is where it takes the time, but I can't see any difference in state between the "slow initial" calls and the "fast" calls.

```cs
// PublisherClient.cs
private void TriggerSend()
{
    //...
    async Task Send()
    {
		// Perform the RPC to server, catching exceptions.
		var publishTask = client.PublishAsync(TopicName, batch.Messages, CallSettings.FromCancellationToken(_hardStopCts.Token)); // <- 20 secs pause
		var response = await _taskHelper.ConfigureAwaitHideErrors(() => publishTask, null);
		Action postLockAction;
```

So I had a couple of questions to help me diagnose a bit more:
* are there possibly any cold-startup-y considerations that I'm ignorant of?
* when trying to reproduce this before, were you using a new project / topic, or one that may have already had a fair few messages / subscribers? 

Thanks again.

**Comment by chrisdunelm** [comment]
In answer to your immediate questions:
* The only cold-start consideration is setting up the network connection(s) - I'll explain more in a moment, as this may be related to the issue you're seeing.
* I was using an existing GCP project, with an existing PubSub topic.

`PublisherClient` will use multiple underlying client, and therefore multiple network connections, and it's possible that you're seeing a delay due to the start-up of those clients/connections.
By default it uses the `Environment.ProcessorCount` network connections (see [PublisherClient.cs](https://github.com/googleapis/google-cloud-dotnet/blob/3c4a0103e2ad6ad3f98c44d7fbb96c0536d3d62e/apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/PublisherClient.cs#L189)).

Is `ProcessorCount` equal to 12 on the machine on which you saw the first 12 messages delayed?
It would be worth configuring the client to use only a single client/connection, and see if the delay is then only for the first message.
This is done by configuring [`ClientCreationSettings.ClientCount`](https://github.com/googleapis/google-cloud-dotnet/blob/3c4a0103e2ad6ad3f98c44d7fbb96c0536d3d62e/apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/PublisherClient.cs#L128) to equal 1 when calling `PublisherClient.CreateAsync(...)`.

Please let me know the result.

**Comment by sm1ke** [comment]
Yes it is exactly as you described - `ProcessorCount` is 12, and setting `ClientCreationSettings.ClientCount` to 1 causes only the first message to take 20s, setting to 2 causes first 2 messages to take 20s, ...

**Comment by chrisdunelm** [comment]
This is probably due to an issue with the networking in your environment.
Startup should take less than 1 second for the first network connection, then considerably less than that for all subsequent connections (as you can see from the timings I posted previously).

If it helps a diagnosis, the underlying network connections are secure http2 channels.
Are you using a proxy, or is is possible you have something on your network that is transparently proxying the traffic, and causing the delay?

Are you able to repeat the test on a machine in a completely different network environment?

**Comment by sm1ke** [comment]
I did previously test on two different networks and different laptops, but let me find some time this week to see if I can rule out proxy/network issues, and get back to you. The fact that I don't see the same delay in the 1.0.0 library also makes me a bit doubtful this is the case? But let me ask some others to see if they see the same behaviour to be sure. Thanks.

**Comment by jskeet** [comment]
I believe this issue needs more information in order to proceed. We'll close it if we haven't heard anything more in about a week - but it can still be reopened if more information is added, of course. (We just don't want a lot of issues hanging around that we can't make any progress on.)

**Comment by sm1ke** [comment]
That sounds very fair - yes please feel free to close. I have a few things I wanted to try, but have not had the chance yet. If I work it out, or find anything else that might give you guys a reasonable chance at reproducing then I will get in touch. Thanks for all the help.
