### ISSUE TITLE
Storage - UploadObjectAsync - "Synchronous operations are disallowed. Call ReadAsync or set AllowSynchronousIO to true instead." (.NET Core 3.0)

### ISSUE THREAD

**Issue by kierenj** [googleapis/google-cloud-dotnet#4109]
Much like https://github.com/googleapis/google-api-dotnet-client/pull/1469, I'm getting:

`Synchronous operations are disallowed. Call ReadAsync or set AllowSynchronousIO to true instead.`

The stack trace I have is:

```c#
   at Google.Cloud.Storage.V1.StorageClientImpl.UploadHelper.CheckFinalProgress()
   at Google.Cloud.Storage.V1.StorageClientImpl.UploadHelper.ExecuteAsync(CancellationToken cancellationToken)
```

My guess is `CheckFinalProgress` is finding and rethrowing an exception from elsewhere in the (comprehensively intimidating) upload infrastructure.

I'm on 2.4.0-beta3. After (a lot!) of paging through releases, I couldn't see anything in the changelogs. In the meantime, I see there's a 2.5.0 now, so I'll update, and set `AllowSynchronousIO=true`.

For others looking to make a one-off exception for a single request:

```c#
var syncIOFeature = HttpContext.Features.Get<IHttpBodyControlFeature>();
if (syncIOFeature != null)
{
    syncIOFeature.AllowSynchronousIO = true;
}
```

**Comment by jskeet** [comment]
Thanks for reporting this. I'll have a look on Monday.

**Comment by kierenj** [comment]
Thank you :) To be explicit, I’m passing the Request stream to the UploadAsync method - proxying an upload, effectively.

**Comment by amanda-tarafa** [comment]
Hi @kierenj, I can reproduce this error with Google.Cloud.Storage.V1 v2.4.0-beta03 but not with v2.5.0. This is expected because v2.5.0 ultimately depends on Google.Apis >= v1.42.0 which contains the fix you referenced in googleapis/google-api-dotnet-client#1469.
If after updating to Google.Cloud.Storage.V1 v2.5.0 you still experience this error, can you please provide us with the smallest possible code snippet that fails for you and as much information as possible about the environment you are running the code in? Also which .NET frameworks you are targeting, the rough size of the objects you are trying to upload, if it happens always or only from time to time etc.
And, about your last comment, what do you mean exactly with  "proxying and upload"?


>

**Comment by kierenj** [comment]
Thanks, I'll try 2.5.0.

By "proxying an upload" I mean that my ASP.NET Core API controller is receiving an upload and in turn uploading it to GCP storage - in effect, it is "proxying" an upload.

**Comment by amanda-tarafa** [comment]
Hi @kierenj have you had time to try 2.5.0?

**Comment by kierenj** [comment]
I have now, yes, thank you - all working as expected :)
