### ISSUE TITLE
Channel integration for Dialogflow - Twilio/ Twitter  -.NET Core

### ISSUE THREAD

**Issue by thinkcodellc** [googleapis/google-cloud-dotnet#4198]
I understand as per Google's notification (https://cloud.google.com/dialogflow/docs/release-notes) that third party integrations from within Dialogflow flow will be shut down. 

Is there a .NET core implementation / can there be .NET core implementation of these external channel integrations made available? Thanks!

**Comment by jskeet** [comment]
I'm not quite sure what you mean, to be honest. Our client library just reflects the public API, and that's all we'd be able to do. I'll look into this more tomorrow, but I doubt that we're going to be able to help.

**Comment by thinkcodellc** [comment]
@jskeet I suppose there is node version of integration with the Dialogflow library to facilitate integration with third party channels which was basically handled from within dialogflow. Wondering if there can be a .NET core version of it? Thanks in advance.

**Comment by jskeet** [comment]
I'm afraid that's not within the remit of our team. I'll enquire internally, but we don't have the resources to put into that ourselves - it's something the Dialogflow team would need to do. I suspect they're choosing to focus *their* resources (which will also be limited) into Node rather than trying to do everything in all languages. I'm going to close this issue now as I really don't think it's going to happen in this repo - I'll pass your request on myself, but you might want to also post in Dialogflow-specific language-neutral support groups to request .NET support.
