### ISSUE TITLE
BigQuery: Implement Scripting API Changes

### ISSUE THREAD

**Issue by d-torres** [googleapis/google-cloud-dotnet#4259]
This is a tracking FR for implementing Scripting API Changes within the BigQuery API.

This work complements the [Routines API](https://github.com/googleapis/google-cloud-dotnet/issues/3762), which allows for the creation/persistence of stored procedures.

Scripts are a form of query that can contain multiple SQL statements, and features such as logic, variable assignments, and related control flow functionality. General documentation about scripting can be found in the [Standard SQL reference pages](https://cloud.google.com/bigquery/docs/reference/standard-sql/scripting).

Reference implementations: [Go](https://code-review.googlesource.com/c/gocloud/+/44311), [Python](https://github.com/googleapis/google-cloud-python/issues/9190) and [Java](https://github.com/googleapis/google-cloud-java/issues/6489).

**Comment by amanda-tarafa** [comment]
I believe this is almost a NoOp for us since:

- We have already added [ListJobsOptions.ParentJobId](https://github.com/googleapis/google-cloud-dotnet/blob/78db7f6b6b5ece85d14448cbd1a6179ac7a9ee26/apis/Google.Cloud.BigQuery.V2/Google.Cloud.BigQuery.V2/ListJobsOptions.cs#L72) which allows to list child jobs of the given parent job only.
- We don't provide a JobsStatistics wrapper class, we expose the Apiary types, so we don't have anything to add there.
- I was going to surface [ScriptOptions](https://cloud.google.com/bigquery/docs/reference/rest/v2/Job#scriptoptions) but as of today, they are not in the [discovery doc](https://github.com/googleapis/google-api-dotnet-client/blob/master/DiscoveryJson/bigquery_v2.json) and so they are not being generated by Apiary.

I've written an integration test for filtering jobs on parent ID which was missing, but that's all.

@d-torres, @shollyman can you confirm we can close this issue (and maybe look into surfacing ScriptOptions)?

**Comment by amanda-tarafa** [comment]
@d-torres, @shollyman I'll be closing this issue via #5003 which adds a test only for the existing parent ID job filtering functionality. I believe there's nothing else we need to do for Scripting. Please reopen if you think otherwise.
