### ISSUE TITLE
Broken links in Spanner ref docs

### ISSUE THREAD

**Issue by mmmarklu** [googleapis/google-cloud-dotnet#4673]
In the [README](https://github.com/googleapis/google-cloud-dotnet/blob/master/README.md) page, there are a few problems with the Spanner ref doc links:

1. Click on [Google.Cloud.Spanner.Common.V1](https://googleapis.dev/dotnet/Google.Cloud.Spanner.Common.V1/3.0.0-beta02/index.html).  You will get a blank page that says "This package is not a product in its own right; this page is present as a root for the API reference documentation"

2. Click on [Google.Cloud.Spanner.Data](https://googleapis.dev/dotnet/Google.Cloud.Spanner.Data/3.0.0-beta02/index.html) and then click on the first link in the page [Google.Cloud.Spanner.Admin.Instance.V1](https://googleapis.dev/dotnet/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Admin.Instance.V1/). You will see 404 error.

**Comment by jskeet** [comment]
The first of these is intentional. The page says exactly what it's there for - and if you click on the API reference link at the top of that page, you'll get the common packages. This isn't a broken link - it's just a matter of a package not being particularly useful in itself.

The second of these is a problem - thanks for pointing it out. It's going to be slightly tricky to fix - it's because in [the equivalent page on GitHub pages](https://googleapis.github.io/google-cloud-dotnet/docs/Google.Cloud.Spanner.Data/index.html) it works fine. The different layout of the different locations is the problem here. I'll probably need to work out something to perform a fix-up of all relative links.

Will look at that on Monday.

**Comment by mmmarklu** [comment]
Thanks for the reply.

Do you know why the ref docs are hosted in two places? googleapis.dev and googleapis.github.io

Are there any differences between the two?

**Comment by jskeet** [comment]
> Do you know why the ref docs are hosted in two places? googleapis.dev and googleapis.github.io

Yes. We've always had them on GitHub pages, and then we added them to googleapis.dev. There are some aspects *not* on googleapis.dev though, so we don't want to turn down GitHub pages yet. (It also takes time and effort to do so, and there have always been higher priority pieces of work.)

> Are there any differences between the two?

The HTML is almost the same on a per-API basis, except for the "All APIs" link that's on GitHub pages but not on googleapis.dev. More importantly, googleapis.dev doesn't have the FAQ, guides etc - because it's intended to be more like "reference material". There's still an open question as to the final information architecture of the docs. In the meantime, I'll try to get the cross-API links fixed - although the docs release process is basically tied to the package release process, so we won't see an update until we do a release.
