### ISSUE TITLE
Pin Cloud Pub/Sub dependencies to minor versions

### ISSUE THREAD

**Issue by kamalaboulhosn** [googleapis/google-cloud-dotnet#4875]
This may already be true for the C# library and if it is, please disregard.

In an attempt to minimize issues caused by bad minor releases in dependencies and to make the rollback procedure for customers easier, we should pin dependencies to a minor version. When new minor versions are released, we should increase the pinned minor version to match the new version in a PR and release a new version of the Pub/Sub client library. If there is no new code in the library, but there are new dependency minor version increments, we should release a new version at least once a month. It is fine to release at a faster cadence than that if desired. This is how things work in the Java library and in fact, the minor version increase PRs are automatically generated. Perhaps thy could be auto generated in C# as well.

**Comment by jskeet** [comment]
I disagree with this. The point of following semantic versioning is that we shouldn't need to do this. If we depend on Grpc.Core 2.27 for example, and a developer wants to use Grpc.Core 2.28, that should be absolutely fine.

More importantly, we need to make sure that we don't prevent users from depending on two different client libraries because they happen to depend on different versions of Grpc.Core... and I definitely don't want to release *every* client library once a month with updated dependencies... ideally I don't want to release *any* library where the only change is dependencies, unless it's also to bump it from a prerelease to a GA release.

Pinning to a specific *major* version might make sense, although we don't currently do this. (Personally I think NuGet should do that by default, but that's a different matter.)

Note that if *we* pin to a specific minor version and someone *else* does exactly the same, then we're introducing a tight coupling between the two - you can't use the latest version of our library unless the other library provider has updated a common dependency too. This feels like it could lead to an arms race of everyone releasing a new version of a library any time any transitive dependency has been updated. That's not a healthy place to be, IMO.

Note that while we *did* encounter user issues with Grpc 2.x being incompatible with Grpc 1.x (which is reasonable), we haven't seen it for minor versions. I would rather not add work that I can see being actively harmful to customers in order to solve something that *isn't* a problem for our customers at the moment as far as we know.

I'll leave this issue open for the moment, but I'm strongly against the proposal.

**Comment by kamalaboulhosn** [comment]
@jskeet We have seen issues with this in other languages like Python. We just had [an issue](https://github.com/googleapis/python-pubsub/issues/75) this week that was caused by a bad change in an underlying dependency. Previously, we have seen this happen in node.js as well. For customers, this type of issue can be quite difficult to understand.

If we pin the Cloud Pub/Sub client library to a minor version and ensure that we have a release of the client library to increase version numbers, then the path to rollback to a working version of the underlying dependency is much clearer; one just needs to roll back the Pub/Sub client library. It will save back and forth with the customer and also improve MTTR for customer pipelines.

**Comment by jskeet** [comment]
Please think beyond a single library. Look at all the libraries produced by this repo: https://github.com/googleapis/google-cloud-dotnet/tree/master/apis

What you're suggesting would mean that if we updated (say) the Grpc.Core dependency in any one of those, then we'd be stopping anyone from using that library with any of the others until the other one is updated - which means *everything* having to be updated, ideally all at once... whenever we want to update *anything* with a new dependency.

That sounds like a much, much worse customer experience which is *very* likely to cause a lot of back and forth. As I say, we haven't experienced this issue yet, in several years of doing this. It's not idiomatic for the .NET ecosystem, and I very strongly believe it would cause significant harm within our community.

**Comment by kamalaboulhosn** [comment]
Is the problem that they are all the same repo? What if we had separate repos for each product as we do in other languages, would that take care of your concerns? This is how it works in Java, with minor version bumps requiring releases of the client library. Is there something inherent to the way .NET dependencies are done that makes it not possible? 

We can say "it hasn't happened yet," but what happens when it does? It has happened in at least two other languages. In one of the cases, the time it took to determine it was caused by an upgraded underlying dependency was days. And it was days without resolution for customers because some of them had trouble downgrading. Users would continue to report the issue even though they said they had downgraded and then we would find out it was because they hadn't actually downgraded. From the interactions I have had with customers, tracking that these dependencies exist and then knowing that a change to one of the dependencies is what caused an issue is very difficult.

If it is possible to do this by having a separate repo for different products, I think that is worth considering.

**Comment by jskeet** [comment]
> Is the problem that they are all the same repo?

No, it's got nothing to do with that. Users don't care which repositories the source code comes from, as they depend on NuGet packages.

> We can say "it hasn't happened yet," but what happens when it does?

Then we can take action at that point, if it ever does. There have been other issues that take days to diagnose, that have nothing to do with versioning. We're good at diagnostics, and I'm confident we can handle it.

But I'm not going to knowingly go against the idiomatic way of expressing dependencies in the .NET ecosystem, adding limitations on the combinations of libraries that our customers can use *just in case* it turns into a problem. I've seen that when those limitations occurred with gRPC in *major* versions, that caused significant pain (where ASP.NET Core used gRPC 2 and we used gRPC 1) - and that was for a single library, where effectively we only had two versions to consider. Trying to pin every dependency would make that problem come up far more often.

The more I've thought about this suggestion, the more trouble I can foresee. I would rather take the risk that we *might* see a problem that we haven't seen in around 4 years of releasing Google Cloud client libraries for .NET, than the near *certainty* that it would cause significant issues. I believe I know the .NET ecosystem and community well enough to make that judgement call.

**Comment by jskeet** [comment]
(Taking discussion private within Google.)
