### ISSUE TITLE
Guide on paging is outdated

### ISSUE THREAD

**Issue by hiranya911** [googleapis/google-cloud-dotnet#4887]
All links and code samples in https://github.com/googleapis/google-cloud-dotnet/blob/master/docs/root/guides/page-streaming.md are broken.

**Comment by jskeet** [comment]
Those documents aren't intended to be read *in GitHub* - they're published into documentation on GitHub pages (currently; they may move).
The page streaming documentation is here: https://googleapis.github.io/google-cloud-dotnet/docs/guides/page-streaming.html

I've checked the links work.

It's unfortunate that I can't easily add a README in that directory to explain the structure, otherwise that would then be treated as documentation too...
Closing as there's no need to fix anything here.

**Comment by hiranya911** [comment]
Thanks for the clarification @jskeet.

Unfortunately search engines most of the time point to the GitHub file as opposed to the rendered html. Hence the confusion.
