### ISSUE TITLE
Support Istio on GKE trace spans in Google.Cloud.Diagnostics.AspNetCore logging

### ISSUE THREAD

**Issue by shaneqld** [googleapis/google-cloud-dotnet#5044]
Hi again,

I'm attempting to associate log entries I write using `ILogger` with trace spans using logging in `Google.Cloud.Diagnostics.AspNetCore`. My environment is Istio on GKE with Istio writing traces (and generating trace IDs and span IDs).

I observe that (at least by default) Istio on GKE is using [Zipkin headers](https://github.com/openzipkin/b3-propagation) such as `X-B3-TraceId` and `X-B3-SpanId`.

Example values:

```
x-b3-traceid: 1234e1419035e455176e926b32d86285 
x-b3-spanid: 4321e68b85da75f0 
```

I note that these values are compatible with [LogEntry](https://cloud.google.com/logging/docs/reference/v2/rpc/google.logging.v2#logentry) `trace` and `span_id` (when converting `X-B3-TraceId` to a resource name).

`GoogleLogger` seems to only support the `X-Cloud-Trace-Context` header, with no ability to extend the behavior.

Ideally I would like to use ILogger and have `LogEntry`'s `trace` and `span_id` set from the Zipkin request headers. I think this would also help others using Istio on GKE.

Would it be possible to support these additional headers and set them appropriately on `trace` and `span_id` when creating `LogEntry`? Or provide an extensibility point somewhere?

Thanks!

**Comment by amanda-tarafa** [comment]
I think we might be able to support this by allowing you to specify (in LoggerOptions) a "GetTraceIdFromRequest" function where you return the GCP traceId built from the information found in the request, i.e., the headers. We can take it from there, we would build the resource name because we have the project ID and we don't need the span ID because the entry is automatically included in the open span (I need to confirm this last bit though).
Let me know if this would roughly meet your needs (I'm not 100% certain that this would work myself, I'd need to test it). This one would require a little more work than #5028 so in any case I wouldn't get to it this week.

**Comment by shaneqld** [comment]
Hi @amanda-tarafa, that approach sounds good to me, although I don't understand why we wouldn't set the span ID if we know it. Surely Stackdriver would face ambiguity when assigning logs to spans in some cases?

**Comment by amanda-tarafa** [comment]
> although I don't understand why we wouldn't set the span ID if we know it

This is the part I need to confirm. If we end up needing the span ID then the function can return something more complex than just the trace ID, but the approach would be the same.

> Surely Stackdriver would face ambiguity when assigning logs to spans in some cases (if we don't specify the span ID)?

As info, we are currently not setting the span ID, even though we have it as well, for Google traces and it hasn't been a problem. In theory, there should not be ambiguity, because a trace (and we do set that) only has an "active" span at any given time. There might be as many open nested spans as needed, but information is always included in the one that was open last (in our implementation, the one at the top of a stack). I have two main concerns though, buffering of log entries and the fact that they are not sent to then backend inmediately when they are written and trace propagation across calls to services made in parallel, and those two scenarios are the ones I want to test. It might very well be that we end up adding the span ID to the entry as well.

I'll update here when I know more.

**Comment by shaneqld** [comment]
Hi @amanda-tarafa, thank you for the explanation and I agree with your concerns.

I have thought about the proposed `GetTraceIdFromRequest` solution and feel that there are use cases outside of logging within HTTP requests. For example, logging against traces in a (non-HTTP) message queue handler.

In the proposed `GetTrace...` method, instead of having `HttpContext` as an argument, an alternative would be to provide an `IServiceProvider`.  The user implementation could then get the `IHttpContextAccessor` service when dealing with HTTP requests, or could retrieve some other scoped service to provide trace information.

**Comment by amanda-tarafa** [comment]
I actually though of a similar but more general approach, which is to define a ITraceContextAccessor that you could register as a service provider. If there's none registered we register our own (the one that supports Google tracing). On GoogleLogger we use whatever is registered to obtain a TraceContext or similar.
I need to take a look though at whether this adds much more complexity to supporting the requested feature or not, the time it will take to develop, etc.

**Comment by amanda-tarafa** [comment]
@shaneqld #5214 Adds this feature. Can you take a quick look and confirm that this will work for you?
You'd have to implement IExternalTraceProvider to return the information on the Zipkin headers and register your provider as a service on application startup.

**Comment by amanda-tarafa** [comment]
This has now been released in https://www.nuget.org/packages/Google.Cloud.Diagnostics.AspNetCore/4.1.0-beta01.
