### ISSUE TITLE
Tracing not working in console app

### ISSUE THREAD

**Issue by tomislavpet** [googleapis/google-cloud-dotnet#5135]
#### Environment details

  - OS: macOS 10.15.2
  - .NET version: .net core 2.2
  - Package name and version: "Google.Cloud.Diagnostics.AspNetCore" Version="4.0.0"

Also referenced in #5018 

Traces don't seem to work when running as a console app. There are no errors, but nothing appears in the GC dashboard. Logging works fine. `GOOGLE_APPLICATION_CREDENTIALS` env variable is pointing to the correct json file.

Code to reproduce it:
```
using System;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.DependencyInjection;
using Google.Cloud.Diagnostics.Common;
using Google.Cloud.Diagnostics.AspNetCore;
using Microsoft.Extensions.Configuration;

namespace Example
{
    public class Program
    {
        public static void Main(string[] args)
        {
            var services = new ServiceCollection();
            var serviceProvider = ConfigureServices(services);

            var app = serviceProvider.GetService<MyService>();

            for (int i = 0; i < 20; i++)
            {
                app.Doit();
            }

            Console.WriteLine("Waiting 10 sec");

            Task.Delay(10000).Wait();

            Console.WriteLine("Done");
        }

        public static IServiceProvider ConfigureServices(IServiceCollection serviceCollection)
        {
            var serviceProvider = serviceCollection.BuildServiceProvider();

            var provider = serviceProvider.GetService<ILoggerProvider>();

            IConfiguration config = new ConfigurationBuilder()
                .AddJsonFile("appsettings.json", true, true)
                .Build();

            serviceCollection
                .AddOptions()
                .Configure<StackdriverOptions>(config.GetSection("Stackdriver"))
                .AddLogging(opt => { opt.AddProvider(GoogleLoggerProvider.Create(null, config["Stackdriver:ProjectId"])).AddConsole().AddDebug(); })
                .AddGoogleTrace(options =>
                {
                    options.ProjectId = config["Stackdriver:ProjectId"];
                    options.Options = TraceOptions.Create(
                        retryOptions: RetryOptions.NoRetry(ExceptionHandling.Propagate),
                        bufferOptions: BufferOptions.NoBuffer(),
                        qpsSampleRate: double.MaxValue
                    );
                })
                .AddSingleton<MyService>();

            serviceProvider = serviceCollection.BuildServiceProvider();

            return serviceProvider;
        }
    }

    public class StackdriverOptions
    {
        public string ProjectId { get; set; }
        public string ServiceName { get; set; }
        public string Version { get; set; }
    }

    public class MyService
    {
        private ILogger m_Logger;
        private IManagedTracer m_Tracer;

        public MyService(ILogger<MyService> logger, IManagedTracer tracer)
        {
            m_Logger = logger;
            m_Tracer = tracer;
        }

        public void Doit()
        {
            using (m_Tracer.StartSpan("test trace"))
            {
                Console.WriteLine("MyService.Doit");

                m_Logger.LogInformation("Doing it!");
                m_Logger.LogWarning("Warning!");
                m_Logger.LogError("Here's an error!");

                Task.Delay(500).Wait();

                Console.WriteLine("MyService.Doit");
            }
        }
    }
}
```

**Comment by amanda-tarafa** [comment]
The package `Google.Cloud.Diagnostics.AspNetCore` is for tracing in ASP.NET Core apps as it relies heavily on the ASP.NET Core application pipeline, in particular on the possibility of defining [middlewares](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-3.1) and executing them as part of each request. The middleware for getting Google Tracing to work out of the box in ASP.NET Core apps is [`Google.Cloud.Diagnostics.AspNetCore.CloudTraceMiddleware`](https://github.com/googleapis/google-cloud-dotnet/blob/master/apis/Google.Cloud.Diagnostics.AspNetCore/Google.Cloud.Diagnostics.AspNetCore/Trace/CloudTraceMiddleware.cs) and that is set up on the call to [`IApplicationBuilder.UseGoogleTrace()`](https://github.com/googleapis/google-cloud-dotnet/blob/909f56870b9e39ac4d75c7092688628f9329efd3/apis/Google.Cloud.Diagnostics.AspNetCore/Google.Cloud.Diagnostics.AspNetCore/Trace/CloudTraceExtension.cs#L81) that you can see [here](https://googleapis.dev/dotnet/Google.Cloud.Diagnostics.AspNetCore/4.0.0/index.html#initializing-tracing). This middleware will execute at the start of every HTTP request and will set up the correct tracer that can later be used through the injected [`Google.Cloud.Diagnostics.Common.DelegatingTracer`](https://github.com/googleapis/google-cloud-dotnet/blob/master/apis/Google.Cloud.Diagnostics.Common/Google.Cloud.Diagnostics.Common/Trace/DelegatingTracer.cs).

Console apps don't have the concept of middleware and you haven't added any code of your own that performs the necessary steps to initialize a tracer, that is, you don't have code equivalent to `Google.Cloud.Diagnostics.AspNetCore.CloudTraceMiddleware` in your console app. The tracer that gets injected is `Google.Cloud.Diagnostics.Common.DelegatingTracer` and this one will just delegate to whatever tracer has been set up before in [`Google.Cloud.Diagnostics.Common.ContextTracerManager`](https://github.com/googleapis/google-cloud-dotnet/blob/master/apis/Google.Cloud.Diagnostics.Common/Google.Cloud.Diagnostics.Common/Trace/ContextTracerManager.cs) (by the middleware in the case of ASP.NET Core apps, by some missing code in the case of your console app) or if none has been set up, it will delegate to [`Google.Cloud.Diagnostics.Common.NullManagedTracer`](https://github.com/googleapis/google-cloud-dotnet/blob/master/apis/Google.Cloud.Diagnostics.Common/Google.Cloud.Diagnostics.Common/Trace/NullManagedTracer.cs) as is your case. `NullManagedTracer` does nothing so it's normal that you are seing no traces.

We don't offer an out of the box solution for Google Tracing in console apps, but as I mentioned on #5018 you can use the functions in [`Google.Clound.Diagnostics.Common.ManagedTracer`](https://github.com/googleapis/google-cloud-dotnet/blob/master/apis/Google.Cloud.Diagnostics.Common/Google.Cloud.Diagnostics.Common/Trace/ManagedTracer.cs) to create your tracers (you can create one tracer to be used for the whole console app execution for instance). You can take a look at what the service initializer and middleware code in `Google.Cloud.Diagnostics.AspNetCore` does, as a guide, but copy-pasting won't work, because as I said, the code in there relies heavily on the ASP.NET Core pipeline. As a rule of thumb, on your console app you should only depend on `Google.Cloud.Diagnostics.Common` and not on `Google.Cloud.Diagnostics.AspNetCore`.

**Comment by amanda-tarafa** [comment]
@tomislavpet I'll close this issue now since I believe I've answered your question. Do please add a comment if you believe otherwise or create new issues for other problems you may find.
