### ISSUE TITLE
Speaker Diarization in C#

### ISSUE THREAD

**Issue by harsh-tukadiya** [googleapis/google-cloud-dotnet#5148]
I want to work with Speaker Diarization in C#, I got an overall idea it will work with Google.Cloud.Speech.V1P1Beta1Google.Cloud.Speech.V1P1Beta1 and I want to work with SpeakerTag.

I just want to know what properties I should enable and use for a better and more accurate result of speaker tag, which works for both longer and shorter audio files. I tried to do it, but speakerTags  are no where near to right solutions

**Comment by shreyshahh** [comment]
waah

**Comment by jskeet** [comment]
The maintainers of this repository are not experts on specific APIs. We're more focused on making sure that the client libraries accurately reflect the underlying API and making sure that the requests you make get to the server, and that the responses from the server are correctly transported to your code.

This question is really about the details of the Speech API itself - so we're really not going to be able to help you.

I would suggest you look at the options on https://cloud.google.com/speech-to-text/docs/getting-support... the `cloud-speech-discuss` group is probably the best approach here.

I'm going to close this issue now as I doubt that what you're seeing is due to the client library. If you have reason to believe that it *is* a client library issue, please add a comment to provide more information.
