### ISSUE TITLE
Implement ListLocations in Google.Cloud.KMS

### ISSUE THREAD

**Issue by flire** [googleapis/google-cloud-dotnet#5247]
Hi!

Are there any plans to implement the method in new KMS library? The old one (Google.Apis.CloudKMS, which, as far as I understand, is not recommended anymore) has this method and I failed to find the replacement in Cloud.KMS.

**Comment by jskeet** [comment]
It's not part of https://github.com/googleapis/googleapis/blob/master/google/cloud/kms/v1/service.proto, which is what the service is generated from.

If it's added to the gRPC service, we can generate it. I suggest you follow one of the support routes on the [KMS support page](https://cloud.google.com/kms/docs/getting-support). I'm going to close this issue now - while I completely understand the desire for the method, there's nothing we can do in this repository until it's part of the gRPC API. (I wouldn't be surprised if it came at a later date via some other route.)

Note that using Google.Apis.CloudKMS should still be fine - it's not the recommended library because Google.Cloud.Kms.V1 provides a better developer experience *for the RPCs it provides*. You should be able to use the two together, using Google.Cloud.Kms.V1 for everything apart from list locations - or you could use Google.Apis.CloudKMS for everything until the method is added to the gRPC library, to avoid having to maintain two dependencies.
