### ISSUE TITLE
Documentation: Document required service account roles

### ISSUE THREAD

**Issue by EatonZ** [googleapis/google-cloud-dotnet#5274]
I have a Cloud Run service deployed using a specific service account. I was implementing logging and tracing today using this library, and spent a while trying to figure out why it wasn't working as expected. I eventually figured out that I needed to add the _Logs Writer_ and _Cloud Trace Agent_ roles to my service account.

Perhaps there are more roles that should be added? [This page](https://cloud.google.com/logging/docs/agent/authorization#create-service-account) mentions _Monitoring Metric Writer_.  I would recommend documenting the required roles somewhere [here](https://googleapis.dev/dotnet/Google.Cloud.Diagnostics.AspNetCore/4.1.0/index.html).

**Comment by jskeet** [comment]
We'll look at this on Tuesday - Monday is a public holiday in the UK.

**Comment by amanda-tarafa** [comment]
@EatonZ We don't usually include this information in the client library documentation but in the API documentation instead since the roles needed for each operation are defined by the API and not by its many client libraries.
You can see the Google Trace API documentation [here](https://cloud.google.com/trace/docs/reference).
Also, the link you are pasting that mentions the monitoring related role is not about using the Diagnostics client libraries or even the underlying APIs, it's about configuring the Logging agent which is a mechanism by which error and std output may be captured and sent to the Cloud Logging service.

**Comment by EatonZ** [comment]
Hi @amanda-tarafa, ok, if you feel that extra documentation isn't needed, you can close this.
I still feel a small note in the Authentication section of [this page](https://googleapis.dev/dotnet/Google.Cloud.Diagnostics.AspNetCore/4.1.0/index.html) wouldn't hurt.🙂

**Comment by amanda-tarafa** [comment]
Ok, what we can do is add there relevants links to where the needed roles are defined. We make the information more easily available but also guaratee that it's up to date (as it is defined by the API and not the client libraries). Would that help?

**Comment by EatonZ** [comment]
Sounds good to me.
