### ISSUE TITLE
Updating trace header

### ISSUE THREAD

**Issue by EatonZ** [googleapis/google-cloud-dotnet#5290]
[Please see this comment from a Google engineer.](https://github.com/GoogleCloudPlatform/esp-v2/pull/252#issuecomment-686884547)

It appears that `traceparent` is going to be the preferred header to use with new code.
I suggest updating [this class](https://github.com/googleapis/google-cloud-dotnet/blob/master/apis/Google.Cloud.Diagnostics.Common/Google.Cloud.Diagnostics.Common/Trace/TraceHeaderContext.cs) with support for the header, with appropriate parsing, validation, etc.

When working with Cloud Load Balancer, it generates and sends both headers to the backend service. Here's an example of what I captured:
```
traceparent: 00-c58cee669d2bbc03412e5f9b230650ce-12db388441ff6da8-00
x-cloud-trace-context: c58cee669d2bbc03412e5f9b230650ce/1358741853276433832
```
The format is a little different.

However, based on t[his table](https://cloud.google.com/trace/docs/setup#recommended_client_libraries), it seems like Google may eventually suggest using OpenCensus, or even OpenTelemetry (when it's out of beta) over this library. Because of that, do you plan on not making any changes here, or will you be making changes to keep this library the recommended one for .NET tracing?

**Comment by amanda-tarafa** [comment]
We are very much aware of the ongoing effort to move to OpenTelemetry, we are tangentially part of it ;).

We won't be making any **related** changes to the Google.Cloud.Diagnostics libraries, at least for the time being and then depending on what the OpenTelemetry library looks like and supports. If and when the `x-cloud-trace-context` header is deprecated there'll be plenty of time to prepare for that.

I'll be closing this FR now, since this is something that we will address when time comes, but not certain whether it'll be in these libraries or somewhere else.
