### ISSUE TITLE
No context provided in AnnotateImageRepsonse

### ISSUE THREAD

**Issue by v0l** [googleapis/google-cloud-dotnet#5467]
## Environment details

  - OS: Ubuntu 20.04
  - .NET version: 3.1.403
  - Package name and version: Google.Cloud.Vision.V1 Version=2.0.0

#### Steps to reproduce

  1. Create a BatchAnnotateImages request with Image.FromFileAsync
  2. Check AnnotateImageResponse context for any information about the file it was processed for
  3. **AnnotateImageResponse.Context is null**

I also tried to specify both Content & Source in Image but i got an error response despite the code documentation saying that Content would take precedence for image analysis, i thought this would allow me to fill the context in the response.. Any ideas?

```
        //     Google Cloud Storage image location, or publicly-accessible image URL. If both
        //     `content` and `source` are provided for an image, `content` takes precedence
        //     and is used to perform the image annotation request.
        [DebuggerNonUserCode]
        public ImageSource Source { get; set; }
```

**Comment by v0l** [comment]
`Status(StatusCode=InvalidArgument, Detail="Only one of image content and uri should be specified.")`

**Comment by jskeet** [comment]
> I also tried to specify both Context & Source in Image but i got an error response

Please show *exactly* what you did for this. Note that "content" and "context" are very different. I would *expect* (but I haven't tried) that if you provide the Context property in the AnnotateImageRequest, that you'd get that same context back in the response. It's not created automatically though - you would need to assign it.

**Comment by v0l** [comment]
Im building the batch like this:

```csharp
var req = new AnnotateImageRequest();
req.Image = await Image.FromFileAsync(fb.path);
//req.Image.Source = new ImageSource();
//req.Image.Source.ImageUri = fb.path;

req.Features.AddRange(new[] {
    Feature.Types.Type.LabelDetection,
    Feature.Types.Type.FaceDetection,
    Feature.Types.Type.ImageProperties,
    Feature.Types.Type.LandmarkDetection,
    Feature.Types.Type.LogoDetection,
    Feature.Types.Type.TextDetection
}.Select((a) =>
{
    var nf = new Feature();
    nf.Type = a;
    return nf;
}));

batch.Requests.Add(req);
```

I also tried with 256 images and it said there where too many images in the request, the docs say you can do up to 2000?

**Comment by jskeet** [comment]
Right the commented out code is trying to specify both a GCS source and file content in the same object. That won't work.

It doesn't look like there's anywhere in the request to specify the original filename. I suggest you file that as a feature request with the Google Cloud Vision team.

> I also tried with 256 images and it said there where too many images in the request, the docs say you can do up to 2000?

That's also very definitely an API issue rather than a client library issue. I'm afraid the maintainers of this repository can't answer questions that are really about the API itself - we're just responsible for making sure that the client library accurately represents the API itself. (There's a small amount of handwritten code in this particular library, but I don't think your question ends up relating to that.)

Please follow one of the routes on the [Google Cloud Vision support page](https://cloud.google.com/vision/docs/getting-support) for both of these questions.

I'll close this issue now because there's nothing we can do from the client libraries side, but I wish you luck.
