### ISSUE TITLE
Unable to set V3.TranslateTextRequest.Contents property - it is marked ReadOnly.

### ISSUE THREAD

**Issue by pavelrybar** [googleapis/google-cloud-dotnet#5644]
Trying to reproduce code in example https://cloud.google.com/translate/docs/advanced/quickstart#translate_v3_translate_text-csharp (rewritten to VB):

```
Dim p As New Google.Protobuf.Collections.RepeatedField(Of String) From {
            "Ciao"
        }

Dim request = New Google.Cloud.Translate.V3.TranslateTextRequest() With {
        .Contents = p, '<--------THIS is marked as error due to readonly property
        .TargetLanguageCode = "en",
        .Parent = New LocationName("infinite-rope-296715", "global").ToString
        }
```
Library metadata attached (renamed *.vb->*.txt)
[TranslateTextRequest.txt](https://github.com/googleapis/google-cloud-dotnet/files/5622071/TranslateTextRequest.txt)

The same problem using NuGet package 2.1.0       

#### Environment details

  - OS: Windows 10 Pro 20H2
  - .NET version: 4.7
  - Package name and version: NuGet Google.Cloud.Translate.V3, Version=2.0.0.0, Culture=neutral, PublicKeyToken=185c282632e132a0"

**Comment by jskeet** [comment]
The property itself is deliberately read-only, but it returns a mutable collection. See [this FAQ entry](https://googleapis.github.io/google-cloud-dotnet/docs/faq.html#how-can-i-modify-repeated-fields-and-maps-in-protobuf-messages) for more details in general.

I'm not sure that VB supports collection initializers within object initializers in the same way that VB does. (At least, I can't find the syntax for it...) One simple workaround is to create the request and then just add to the contents:

```vb
Dim request = New Google.Cloud.Translate.V3.TranslateTextRequest() With {
    .TargetLanguageCode = "en",
    .ParentAsLocationName = New LocationName("infinite-rope-296715", "global")
}
request.Contents.Add("ciao")
```

(Note that I've used the `ParentAsLocationName` property instead of `Parent`; I recommend using the strongly-typed resource names where possible.)

**Comment by pavelrybar** [comment]
Thank you for solution.
