### ISSUE TITLE
Google.Cloud.Logging.Nlog - Log correlation with traces

### ISSUE THREAD

**Issue by orchowski** [googleapis/google-cloud-dotnet#5677]
Hi!

**Is your feature request related to a problem? Please describe.**
I can't correlate stackdriver logs in the tracing panel inside the google console.
![image](https://user-images.githubusercontent.com/17548765/101622328-33a45a80-3a17-11eb-9363-83ea54ee1b0b.png)

I think that's because of the lack of fields like **trace**, **traceId** mentioned here https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry

I tried to find in code place where LogEntry is filled and eg. field **trace** exist, but it's skipped at **GoogleStackdriverTarget** during object creation.

`          var logEntry = new LogEntry
            {
                Severity = s_levelMap[loggingEvent.Level],
                Timestamp = ConvertToTimestamp(loggingEvent.TimeStamp),
                LogName = _logName,
                Resource = _resource,
            };
`
And at other places, algorithm flow fills labels, resources section, and nothing else.

 **Describe the solution you'd like**
Giving the possibility to fill LogEntry fields required for tracing.

If it's possible to then sorry for asking. However, in this case, documentation should be updated.

**Comment by jskeet** [comment]
Assigning to Amanda who knows more about the relationship between logging and tracing than I do. I strongly suspect this will be tricky to do without just providing some kind of interface (to be implemented by the user) for "here's how I discover the current trace".

**Comment by orchowski** [comment]
@jskeet or by convention. Do you want to place a trace in the log entry? Then we can look at the JSON payload and assign the same values to it.
**trace** from payload -> **trace** inside logEntry

Less complicated i think. Or it'd be better to copy these fields from contextproperties

**Comment by amanda-tarafa** [comment]
We do this automatically for the Google.Cloud.Diagnostics.AspNetCore* libraries, which do both tracing and logging (not suggesting you change to that by the way). I'd have to take a look at the NLog lib in more detail, to confirm the best way to do this, but I believe that indeed, something as what @jskeet  suggests will be necessary, and then we can obtain the trace values provided by that user implemented interface and add them to the LogEntry. I could look into providing an out of the box implementation of that interface for Google Cloud Trace.
I'll take a look this afternoon and confirm.

**Comment by jskeet** [comment]
@orchowski: I don't think I'd want to tie this to using a JSON payload. It would *perhaps* be reasonable to have a property that could be specified in NLog entries that would be extracted automatically, but I'm not sure yet.

**Comment by amanda-tarafa** [comment]
OK, first for associating log entries to traces we are talking about three values: `TraceId`, `SpanId` and `TraceSampled` (false indicates either that the trace was not sampled on the backend or that whether it was sampled or not was unknown at the time of writing the log entry). `SpanId` and `TraceSampled` don't need to be set, but if we are going to add the feature, we should support it fully. For the two options discussed above (properties and interface) we would define the type `TraceContextForLogEntry` that would contain these 3 values.

As for the options some intial rought thoughts (granted I might be missing a lot here, since I'm not very familiar with NLog):

* Have a special property that if detected we extract a `TraceContextForLogEntry` and set the corresponding values in the LogEntry. This is fairly straightforward both for us to implement and for users to use. Still there a few loose ends:
  * Should that property be "removed" after use so that it's not added to the "normal" set of properties?
  * What if we remove it and there are references to it on layout, implying that the user expects to see it on the "normal" property set or somewhere else.
  * What if we don't remove it, and it's also added as normal property?
  * Should we add a config flag to remove it from normal properties?

  I end up not liking adding "special" properties. This is something that could snowball if similar requests start to come in.

* Have a `ITraceContextProvider` interface that users can implement and specify the type of their implementation in the config file. The problem here is how to inject this provider into the `GoogleStackdriverTarget`. And more importantly, how to inject it in a way that this provider can get its own dependencies through DI. Injecting dependencies in NLog is not [straightforward](https://github.com/NLog/NLog/wiki/Dependency-injection-with-NLog) and requires user code for configuring the logger, appart from the XML config file.
  * I'm favouring using NLog DI to inject an `Microsoft.Extensions.DependencyInjection.IServiceProvider` from which we can obtain the `ITraceContextProvider` implementation that the user specifies in config. We would have to take a dependency on `Microsoft.Extensions.DependencyInjection` though. (I'm thinking that users can wrap their own DI mechanism on an implementation of IServiceProvider)
  * An alternative is to have the user directly inject the `ITraceContextProvider` using NLog DI mechanism, but if other similar providers are needed in the future, constructor overload will explode. And we would be pushing solving DI to the user very strongly.

Thoughts welcome.

**Comment by snakefoot** [comment]
For NLog the expected approach would be the use of Layout-properties on GoogleStackdriverTarget.

The user can then configure the Layout-property to use the wanted layoutrenderer, and the user can also register [custom layoutrenderers](https://github.com/NLog/NLog/wiki/How-to-write-a-custom-layout-renderer) to capture context.

**Comment by amanda-tarafa** [comment]
@snakefoot thanks for the info. It did feel like I was going down a rabbit hole earlier. I'll reply in more detail tomorrow.

**Comment by amanda-tarafa** [comment]
@orchowski I might be able to work on this some next week, but I can't be sure right now. If it's not next week, then I won't get to it till next year.

@snakefoot , again, thanks for the info.

> Maybe create a new NLog specific nuget-package that knows about `Google.Cloud.Diagnostics.Common.ContextTracerManager` and `Google.Cloud.Diagnostics.Common.TraceHeaderContext`.

We probably wound't do that. After all, Google.Cloud.Diagnositcs.* is just one way in which traces can be managed. We even, recently, got a feature request (#5044) to support external traces in the logging component of Google.Cloud.Diagnostics.*.

I've been thinking more about providing some out of the box trace provider for Google Cloud Trace in the NLog lib, and really, we could only (reliably) get the trace context as specified on the headers of the request, but that wouldn't be accurate because more spans could have been created during the request (through Google.Cloud.Diagnostics.* or anything else). So I feel more confortable adding an example showing how to extract the Google Cloud Trace info from headers and configure NLog to include those in the log entry than anything else.

> Notice Microsoft DotNet have something called `System.Diagnostics.Activity.Current` that contains TraceId + SpanId. If Google-Cloud integrated nicely with `System.Diagnostics.Activity.Current` then [NLog.DiagnosticSource](https://www.nuget.org/packages/NLog.DiagnosticSource) might be all you need.

Yep, something that we might look at in the future, but not soon enough to address this FR.

**Comment by snakefoot** [comment]
> @amanda-tarafa get the trace context as specified on the headers of the request

The NLog.Web.AspNetCore-nuget-package contains a layoutrenderer called [${aspnet-request-headers:HeaderNames=MyHeaderName}](https://github.com/NLog/NLog/wiki/AspNetRequest-Headers-Layout-Renderer). Maybe it is just a matter of transforming the contents of the Google-Request-Header ?

**Comment by snakefoot** [comment]
Created #6024 as an example of how to implement this.

**Comment by amanda-tarafa** [comment]
@orchowski, can you take a look at @snakefoot's PR #6024 and check that something like that would work for you. We can resolve separately the matter of how to extract Google Trace Trace Id and Span Id from the header or provide it in any other way.
Thanks!

**Comment by orchowski** [comment]
Ok but tomorrow

**Comment by amanda-tarafa** [comment]
Yep no rush at all.

**Comment by amanda-tarafa** [comment]
Reopening, I'll add documentation before closing.

**Comment by snakefoot** [comment]
Guess with help from [NLog.Web.AspNetCore](https://www.nuget.org/packages/NLog.Web.AspNetCore/) then one could do this:

```c#
[LayoutRenderer("aspnet-google-traceid")]
[ThreadSafe]
public class GoogleManagedTracerRenderer : AspNetLayoutRendererBase
{
      protected override void DoAppend(StringBuilder builder, LogEventInfo logEvent)
      {
           var managedTracer = HttpContextAccessor?.RequestServices?.GetRequiredService<IManagedTracer>();
           string traceId = managedTracer?.GetCurrentTraceId();
           if (!string.IsNullOrEmpty(traceId))
           {
               builder.Append(traceId);
           }
           else
           {
               // TODO Make fallback to System.Diagnostics.Activity.Current
           }
      }      
}

[LayoutRenderer("aspnet-google-spanid")]
[ThreadSafe]
public class GoogleManagedTracerRenderer : AspNetLayoutRendererBase
{
      protected override void DoAppend(StringBuilder builder, LogEventInfo logEvent)
      {
           var managedTracer = HttpContextAccessor?.RequestServices?.GetRequiredService<IManagedTracer>();
	   ulong? spanId = managedTracer?.GetCurrentSpanId();
           if (spanId > 0)
           {
               builder.Append(spanId.Value.ToString("X"));
           }
           else
           {
               // TODO Make fallback to System.Diagnostics.Activity.Current
           }
      }      
}
```

**Comment by amanda-tarafa** [comment]
Ah but that requires a dependency on Google.Cloud.Diagnostics.Common for the managed tracer.
I was thinking that with the layout renderer you mentioned a few comments up for accessing headers of ASP.NET Core requests and the replace layout renderer, you don't need the dependency and can probably skip having to write these classes. I haven't had time to test this though.
Here's the [regular expression](https://github.com/googleapis/google-cloud-dotnet/blob/f5535114700b9a736486db7f488562706bca2366/apis/Google.Cloud.Diagnostics.Common/Google.Cloud.Diagnostics.Common/Trace/TraceHeaderContext.cs#L48) for it.

**Comment by snakefoot** [comment]
Yes using the header `X-Cloud-Trace-Context` directly would be more elegant:

> X-Cloud-Trace-Context: 6518720b40e1efacf2299758d229210a/14866474463603563926

That uses the following format:

> "X-Cloud-Trace-Context: TRACE_ID/SPAN_ID;o=TRACE_TRUE"

https://cloud.google.com/trace/docs/setup#force-trace

Maybe one could apply [${replace:regex=true}](https://github.com/NLog/NLog/wiki/Replace-Layout-Renderer) around [${aspnet-request-headers:headerNames=X-Cloud-Trace-Context}](https://github.com/NLog/NLog/wiki/AspNetRequest-Headers-Layout-Renderer)

**Comment by amanda-tarafa** [comment]
Yep exactly those were my thoughts. Using a very similar regex to the one we have in Diagnostics, the one I linked above, I was thinking it could be possible to capture and replace by empty everything but the trace ID, then everything but the span ID and then everything but the sampling mask. I see if I can try that soon.

**Comment by snakefoot** [comment]
Maybe something like this:

```xml
<variable name="cloud-trace-regex" layout="^([A-Fa-f0-9]\{32}\)/([0-9]+)\$" />
<variable name="cloud-trace-header" layout="${aspnet-request-headers:headerNames=X-Cloud-Trace-Context}" />
<variable name="cloud-trace-traceid" layout="${replace:inner=${cloud-trace-header}:regex=true:searchFor=${cloud-trace-regex}:replaceWith=\$0}" />
<variable name="cloud-trace-spanid" layout="${replace:inner=${cloud-trace-header}:regex=true:searchFor=${cloud-trace-regex}:replaceWith=\$1}" />
```

Alternative to the slow RegEx could be this more crude way:

```xml
<variable name="cloud-trace-header" layout="${aspnet-request-headers:headerNames=X-Cloud-Trace-Context}" />
<variable name="cloud-trace-traceid" layout="${substring:inner=${cloud-trace-header}:length=32}" />
<variable name="cloud-trace-spanid" layout="${substring:inner=${cloud-trace-header}:start=33:length=16}" />
```

**Comment by amanda-tarafa** [comment]
This has been released in [Google.Cloud.Logging.NLog v3.3.0](https://www.nuget.org/packages/Google.Cloud.Logging.NLog/3.3.0).
Thanks @orchowski for the request and @snakefoot for the work!

**Comment by danielwinkler** [comment]
@snakefoot Thanks for the idea, I implemented your recommendation but have some suggestions for future reference:

- we need an offset already for the trace id extraction as the extracted value includes the header name
- instead of `layout` we should use `value` in the `variable` definition

```xml
<variable name="cloud-trace-header" value="${aspnet-request-headers:headerNames=X-Cloud-Trace-Context}" />
<variable name="cloud-trace-traceid" value="${substring:inner=${cloud-trace-header}:start=22:length=32}" />
<variable name="cloud-trace-spanid" value="${substring:inner=${cloud-trace-header}:start=55:length=16}" />
```

@amanda-tarafa Thank you for all your support around here. I just wanted to add that it was really hard for me to wire everything together. It would be nice if there would be a bit more documentation on how to connect google logging and tracing, e.g. on the google nlog package some information on how to use the google tracing header.

**Comment by snakefoot** [comment]
@danielwinkler Thank you for the feedback. Have fixed my original post, sorry about the confusion.

**Comment by amanda-tarafa** [comment]
@danielwinkler I'll try to add some docs when I'm back in the office in January. Thanks!
