### ISSUE TITLE
Remove dependency for libdl from .net 5 pubsub library

### ISSUE THREAD

**Issue by michaelcastle** [googleapis/google-cloud-dotnet#5828]
I've recently updated my project to .net 5.0 and use Google.Cloud.PubSub.V1 2.2.0. I run the code in a linux docker container.

Since the upgrade to .net 5 I have an error when attempting to check if a topic exists and create it if it doesn't, using the following code

`var topicName = TopicName.FromProjectTopic(gcpPubSubSettings.ProjectId, topicId);`
`var publisher = await PublisherServiceApiClient.CreateAsync(cancellationToken).ConfigureAwait(false);` 

In the last line I now get the following error.

> System.DllNotFoundException: Unable to load shared library 'libdl.so' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibdl.so: cannot open shared object file: No such file or directory
>    at Grpc.Core.Internal.UnmanagedLibrary.Linux.dlopen(String filename, Int32 flags)
>    at Grpc.Core.Internal.UnmanagedLibrary.LoadLibraryPosix(Func`3 dlopenFunc, Func`1 dlerrorFunc, String libraryPath, String& errorMsg)
>    at Grpc.Core.Internal.UnmanagedLibrary.PlatformSpecificLoadLibrary(String libraryPath, String& errorMsg)
>    at Grpc.Core.Internal.UnmanagedLibrary..ctor(String[] libraryPathAlternatives)
>    at Grpc.Core.Internal.NativeExtension.LoadUnmanagedLibrary()
>    at Grpc.Core.Internal.NativeExtension.LoadNativeMethods()
>    at Grpc.Core.Internal.NativeExtension..ctor()
>    at Grpc.Core.Internal.NativeExtension.Get()
>    at Grpc.Core.Internal.NativeMethods.Get()
>    at Grpc.Core.GrpcEnvironment.GrpcNativeInit()
>    at Grpc.Core.GrpcEnvironment..ctor()
>    at Grpc.Core.GrpcEnvironment.AddRef()
>    at Grpc.Core.Channel..ctor(String target, ChannelCredentials credentials, IEnumerable`1 options)
>    at Google.Api.Gax.Grpc.GrpcCore.GrpcCoreAdapter.CreateChannelImpl(String endpoint, ChannelCredentials credentials, GrpcChannelOptions options)
>    at Google.Api.Gax.Grpc.GrpcAdapter.CreateChannel(String endpoint, ChannelCredentials credentials, GrpcChannelOptions options)
>    at Google.Api.Gax.Grpc.ClientBuilderBase`1.CreateChannel(String endpoint, ChannelCredentials credentials)
>    at Google.Api.Gax.Grpc.ClientBuilderBase`1.CreateCallInvokerAsync(CancellationToken cancellationToken)
>    at Google.Cloud.PubSub.V1.PublisherServiceApiClientBuilder.BuildAsyncImpl(CancellationToken cancellationToken)
>    at Optii.Infrastructure.InternalServices.Domain.Pubsub.GcpPubSub.PubSubClient.PublisherServiceApiClientAsync(CancellationToken cancellationToken) in C:\Users\Michael\Documents\reporting-svc\Optii.Infrastructure.InternalServices\Domain\Pubsub\GcpPubSub\PubSubClient.cs:line 25
>    at Optii.Infrastructure.InternalServices.Domain.Pubsub.GcpPubSub.Subscription`2.CreateTopicIfNotFound(CancellationToken cancellationToken) in C:\Users\Michael\Documents\reporting-svc\Optii.Infrastructure.InternalServices\Domain\Pubsub\GcpPubSub\Subscription.cs:line 161
>    at Optii.Infrastructure.InternalServices.Domain.Pubsub.GcpPubSub.Subscription`2.AddSubscriptionAndHandler(CancellationToken token) in C:\Users\Michael\Documents\reporting-svc\Optii.Infrastructure.InternalServices\Domain\Pubsub\GcpPubSub\Subscription.cs:line 107
>    at Optii.Infrastructure.InternalServices.Domain.Pubsub.GcpPubSub.Subscription`2.<>c__DisplayClass10_0.<<AddResilientSubscriptionAndHandler>b__6>d.MoveNext() in C:\Users\Michael\Documents\reporting-svc\Optii.Infrastructure.InternalServices\Domain\Pubsub\GcpPubSub\Subscription.cs:line 89
> 

To fix the issue I have had to add to my docker file the _libgdiplus_ library
`RUN apt-get update \ 
    && apt-get install -y --no-install-recommends libgdiplus libc6-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
RUN ln -s /usr/lib/libgdiplus.so /usr/lib/gdiplus.dll`

But this is a bit of a pain and causes other issues because of the way we run the application.

Is it possible to remove the dependency on this library?

**Comment by jskeet** [comment]
I strongly suspect this isn't really a dependency on libgdiplus itself - I suspect it's just that adding libgdiplus adds libc-dev, which is what the native gRPC code depends on.

No, we're not going to remove our dependency on Grpc.Core - gRPC is the underlying transport the libraries use, and it's fundamental to the libraries.
It *is* possible to use the Microsoft gRPC implementation, but for PubSub in particular we use some GCP-specific extensions which aren't supported in the MS implementation.

In the future we *may* move to only the MS implementation, but there's an issue there in terms of platform support - it requires .NET Core 3.1 or higher, whereas we support .NET Framework 4.6.1 as well.

This is an area we would like to streamline, so that folks who are able to use the MS implementation can do so without the Grpc.Core dependency at all, but it's a complex area - certainly not just a matter of removing the dependency.

See https://github.com/grpc/grpc/pull/24485 for more details of the underlying gRPC issue. We haven't updated the Grpc.Core dependency to 2.34.0 (which has the fix in) because that has signing issues in .NET Framework, which should be solved in 2.35.0.

But as you're running on .NET 5, I believe a simpler fix for you *should* be available just by adding an explicit dependency on Grpc.Core 2.34.0, which shouldn't cause any Windows-only signing issues, unless you *also* run your application on Windows.

I'll close this issue now as we don't intend to remove the dependency on Grpc.Core - we basically can't - and this comment contains a simpler workaround than your current one.

**Comment by michaelcastle** [comment]
Thanks for the quick response, workaround and explanation.

**Comment by livesankp** [comment]
This work around works. Thanks @jskeet

**Comment by jskeet** [comment]
@andmos: Using .NET 8, you shouldn't need Grpc.Core at all - it should be using Grpc.Net.Client. If it's easy to do, could you file a new issue with some repro steps so we can look into it? (I really don't want users to have to add a dependency on Grpc.Core.)

**Comment by andmos** [comment]
Thanks for the reply @jskeet - I tested replacing the reference on Grpc.Core with Grpc.Net.Client, it went back to failing. I'll open a new issue with the information I have to go on here. Thanks!

**Comment by andmos** [comment]
Hope this is helpful @jskeet: https://github.com/googleapis/google-cloud-dotnet/issues/11779
