### ISSUE TITLE
[Spanner] ClrType `decimal` is currently mapped by default to `FLOAT64`

### ISSUE THREAD

**Issue by olavloite** [googleapis/google-cloud-dotnet#5837]
The .NET `decimal` ClrType is [currently mapped](https://github.com/googleapis/google-cloud-dotnet/blob/34b71e8b87efdbc3043906d9b2dd7d1b8e9bb43d/apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/SpannerDbType.cs#L279) to the Spanner `FLOAT64` data type. That is correct in the sense that both are floating point types. It does however not correspond with the default mapping for other database systems:
1. SQL Server maps it to `DECIMAL(29,4)`
2. PostgreSQL maps it to `numeric` (which is a fixed point exact type)
3. MySQL maps it to `decimal` (which is a fixed point exact type).

This might cause some surprises for users moving from other DBMS'es to Spanner. We should consider changing the default mapping to `NUMERIC`.

**Comment by jskeet** [comment]
It sounds like that could break users who are currently using FLOAT64. The FromClrType method looks like it's only called by SpannerParameter.SpannerDbType, if the type hasn't been set explicitly. So I can see that change causing a problem if someone were trying to update a FLOAT64 column, and only specifying the value (as a decimal). Does that sounds correct as a compatibility issue?

We could make this a [connection string option](https://googleapis.dev/dotnet/Google.Cloud.Spanner.Data/latest/connection_string.html), defaulting to the current behavior in the current major version, but changing the default to `NUMERIC` in a later major version.

**Comment by jskeet** [comment]
(Assigned to @olavloite just so that it *has* an assignee, but we don't need to decide just yet who will make the change.)

**Comment by olavloite** [comment]
> Does that sounds correct as a compatibility issue?

Yes, but I think that Spanner will [automatically coerce](https://cloud.google.com/spanner/docs/conversion_rules) that value to a `FLOAT64` server side. I'll try to see if I can test that to verify if my assumption is right.

**Comment by amanda-tarafa** [comment]
But even if Spanner coerces the NUMERIC value to FLOAT64, the potential precission loss has already happened, just because of going through NUMERIC first? So, the surprise might not be a conversion error, but (arguiably worst) a silent loss of precission?
Or am I missing something?

**Comment by olavloite** [comment]
1. In the [current implementation](https://github.com/googleapis/google-cloud-dotnet/blob/42669a736bf56e8f02873d03dfa9d549340d6957/apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/SpannerDbType.ValueConversion.cs#L169) the `decimal` value will be converted to a `double`. This conversion [can loose precision](https://www.geeksforgeeks.org/decimal-todouble-method-in-c-sharp/#:~:text=This%20method%20is%20used%20to,significant%20digits%20than%20a%20Decimal.).
2. If we were to change the default mapping a `decimal` value would be converted to a `SpannerNumeric`. That conversion can  also lose precision. The [default conversion at this moment](https://github.com/googleapis/google-cloud-dotnet/blob/42669a736bf56e8f02873d03dfa9d549340d6957/apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/SpannerDbType.ValueConversion.cs#L224) will throw an error if there is loss of precision (which means that we would have to change that behavior for this specific conversion if we would not want an error in such a case).

I'm not familiar enough (and haven't dug into) the specifics of `decimal` to know which of the conversions from `decimal` to `double` and from `decimal` to `SpannerNumeric` is most likely to loose precision.

**Comment by amanda-tarafa** [comment]
I think the worry is not that there might be precission loss (it's actually unavoidable unless we had 1 to 1 type mapping). My worry would be that this would introduce a _different_ type of precission loss. If someone using decimals to update a FLOAT64 column (clr double and Spanner FLOAT64 seem to be the same, so converting to double has not added "extra" precission loss) has worked around _that_ precission loss, they'd now would start seing (potentially) precission loss because we would be going from decimal to NUMERIC to FLOAT64, and the decimal to NUMERIC step may loss precission differently than the decimal to FLOAT64 step.
Mind you, I'm not making the case for not doing the change, I'm making the case for considering it a breaking change and going with an opt in approach like the one proposed by @jskeet until we are ready to bump the major version.

**Comment by amanda-tarafa** [comment]
Apart from breaking change issues described above, this one becomes a problem after introducing PgNumeric. Spanner numeric and PG numeric do not coexist, they are alternates, but we don't know if we are working with a Spanner or PG database at any given point.
Sooner rather than later we'll need that signal coming from the connection string if we want to have better type mappings defaults. The issue described in this thread would benefit from that, but also:

- When converting ADO.NET `DbType.VarNumeric` to a `SpannerDbType`. `DbType.VarNumeric` represents both Spanner numeric and Pg Numeric, but we can't tell which, so we default to Spanner numerci which is wrong. See https://github.com/googleapis/google-cloud-dotnet/pull/8261#discussion_r834881070

On top of PG vs. Spanner signal, we can add extra type mapping configuration to the connection string.

**Comment by olavloite** [comment]
Regarding dialect in the connection string: We decided to implement automatic dialect detection in some other clients. The actual detection is executed asynchronously to prevent it from slowing down opening a connection, and cached for a given database id.

The dialect can be queried like this:

```sql
select option_value
from information_schema.database_options
where option_name='database_dialect'
```

**Comment by amanda-tarafa** [comment]
Yep that could work as an alternative to have it on the connection string. Still, and this is an issue with either approach, there's the problem of making it available outside the scope of a connection, for instance, depending on how you build a SpannerParameter, you might not know whether it's going to be used in a PG or Spanner command.

I'll draft a doc for this in a couple of weeks and we can go from there.

**Comment by Rishabh-V** [comment]
This is now complete via #8534 and #8656
