### ISSUE TITLE
Error while loading assemblies: /Users/runner/.nuget/packages/grpc.core/2.34.0/runtimes/win/native/grpc_csharp_ext.x64.dll

### ISSUE THREAD

**Issue by smdelacruz** [googleapis/google-cloud-dotnet#5856]
We want to build our Xamarin iOS using Microsoft Azure Hosted agent with MacOS VM but we are having an error when it tries to load the GRPC assemblies.

The closes error I saw on the web regarding this issue is [GRPC error](https://github.com/googleapis/google-cloud-dotnet/issues/1186#issuecomment-313594914) which was closed long time ago. 

#### Environment details

  - OS: Macos-latest
  - .NET version: 2.0
  - grpc 2.34
  - grpc.core 2.34
  - Xamarin.iOS 14.6.0.15

There are not so much information and not so much resources with the same error on the web.
 Any help is greatly appreciated

**Comment by jskeet** [comment]
I don't see any relation to the Google Cloud Client Libraries in this question, and Xamarin isn't a supported platform for those libraries anyway, so I'm going to close this issue. However, I may still be able to help you in passing, so to speak.

I know that Grpc.Core split out its mobile support into separate packages as of Grpc.Core 2.34.0, so that may well be the problem. There's a new Grpc.Core.Xamarin package which you need to add into your dependencies - see https://github.com/grpc/grpc/blob/master/src/csharp/experimental/README.md for more details.

If this isn't enough to help you, please file a new issue in https://github.com/grpc/grpc which is the right repo for gRPC-specific issues.

**Comment by smdelacruz** [comment]
@jskeet Thank you for the suggestion. I have created this issue https://github.com/grpc/grpc/issues/25202.
