### ISSUE TITLE
INFO: Unit testing techniques for code using GC libraries

### ISSUE THREAD

**Issue by jimfum** [googleapis/google-cloud-dotnet#5881]
I've been searching a lot but getting good enough information or guidance around how to unit test code that uses google cloud library in .NET has been so far hidden from me. Hope you could point me to the right direction.

As the interaction with the library is through static methods it makes it harder to abstract. GC library isn't the only one doing it this way (actually many basic .NET framework classes do the same) and I've always been wondering why that is.

The techniques I'm aware of are:

- Wrapping the needed GC calls in my classes with interfaces that I can mock.
- I've heard about GC local emulator but that sounds more like for integration testing and with setup not being super trivial.
- Using assembly shim techniques like Microsoft Fakes but that sounds quite complicated too (plus it's only in Visual Studio Enterprise).

None of the above seems good from a simplicity point of view.

Quickly looking around there seems to be a solution for Python with testbeds (https://github.com/GoogleCloudPlatform/appengine-gcs-client/issues/21) and Java also seems to have something (https://cloud.google.com/appengine/docs/standard/java/tools/localunittesting).

Thank you.

**Comment by jskeet** [comment]
Please could you clarify what you mean by "google cloud library"? We have many, many packages, and it would be helpful if we could talk about one very concrete package to avoid miscommunicating.

The gRPC-based packages generally expose an abstract class with virtual methods on - so you could write your own fake or mock based on that.

You talk about "interaction with the library through static methods" - typically there's the `XyzClient.Create` method, but that would usually be the only static method involved, and that's precisely the part you'd replace in order to inject your fake. That's why more concrete details would be helpful.

**Comment by jimfum** [comment]
Hi jskeet, thanks for a prompt reaction. We can be specifically talking about `Google.Cloud.PubSub.V1` and `Google.Cloud.Storage.V1`. 

Spot on, the main issue is typically the static `XyzClient.Create` (static being a problem) and that it doesn't return a type of an interface but a class (possibly a problem although they are ways to mock classes without interfaces, not sure they're applicable in this case though) - what would be the technique to mock that? (using `Moq` in my case)

When using PubSub, these are currently the ones we'd need to mock - `SubscriberClient.CreateAsync`, `PublisherServiceApiClient.CreateAsync`, `SubscriberServiceApiClient.CreateAsync`.

**Comment by jskeet** [comment]
The fact that the creation methods return a class rather than an interface *shouldn't* be a problem - because they're abstract classes. I'd expect any decent mocking library to cope with that, and we mock them in unit tests.

You shouldn't need to mock the creation methods at all - instead, inject the *results* of those creation methods, and put the calls to the actual creation methods into the production setup code. Your tests would create the relevant fakes/mocks, then pass those in in whatever way the production code would.

PubSub is more complex than most other libraries as there's the separation between the "raw API clients" and the wrappers that make them perform well. But `SubscriberClient` and `PublisherClient` are *also* abstract classes, so you could either fake `SubscriberClient`, or create a `SubscriberClientImpl` using fake `SubscriberServiceApiClient` instances depending on exactly what you want to do. I'd expect faking `SubscriberClient` to be the simplest approach for most applicatoins.

I'll readily acknowledge that none of this is massively simple - but that's to be expected given the complexity of the API itself. How complex your tests need to be will depend on what you're trying to test.

**Comment by jimfum** [comment]
Thanks again. I'm still missing a piece here:
```csharp
using Google.Cloud.Storage.V1;
public class MyApp {
   public MyApp() {
      var client = StorageClient.Create();
      ...
      client.UploadObjectAsync(...);
   }
}
```
The client I'm getting from StorageClient.Create() needs to be my mocked client because really, I don't want to call the real client that touches the cloud - instead I want to mock the call and its result and as far as I know I cannot inject/replace code that's behind a static call. Still the only solution that comes to mind is to create my own wrapper around StorageClient that implements my interface. 
```csharp
public class MyApp {
   public MyApp(IMyWrapperAroundStorageClient wrappedStorageClient) {
      var client = wrappedStorageClient.Create();
      ...
      client.UploadObjectAsync(...);
   }
}
```
So now I can return my mocked client and have UploadObjectAsync return whatever mocked data I want.

I'm happy to learn if there's a testing/mocking framework that simplifies this or offers alternative.

**Comment by jskeet** [comment]
The idea is to have something half way between: inject the dependency (StorageClient) rather than initializing it in the constructor:

```csharp
public class MyApp {
   public MyApp(StorageClient storageClient) {
      ...
      storageClient.UploadObjectAsync(...);
   }
}
```

... and use the fact that `StorageClient` is just an abstract class to use mocking - or other test double approaches, such as a fake - to make it testable.

Your production code would call `StorageClient.Create()` to pass the client into the constructor, whereas your test code pass in the fake.

**Comment by jimfum** [comment]
Got it. Will give that a try. Didn't think I could be faking an abstract class as I'm used to do that with interfaces. Also I hope ASP.NET Core dependency injection will be able to inject the real client into the constructor for production.

Much appreciated.

**Comment by jskeet** [comment]
> Also I hope ASP.NET Core dependency injection will be able to inject the real client into the constructor for production.

That much is easy. [Here's an example](https://github.com/GoogleCloudPlatform/functions-framework-dotnet/blob/master/examples/Google.Cloud.Functions.Examples.StorageImageAnnotator/Function.cs) I use in the Functions Framework, using ASP.NET Core dependency injection for Storage and the Vision API:

```csharp
        public override void ConfigureServices(WebHostBuilderContext context, IServiceCollection services) =>
            services
                .AddSingleton(ImageAnnotatorClient.Create())
                .AddSingleton(StorageClient.Create());
```

**Comment by jimfum** [comment]
@jskeet so far so good and quite clean. However, `SubscriberClient.CreateAsync(subscriptionName)` is tougher. Because of the argument that in my case is known only at runtime and within the same class that calls it, I cannot extract it our and inject the same way as `SubscriberServiceApiClient` where we call just `SubscriberServiceApiClient.Create()`.

**Comment by jskeet** [comment]
So you might want to wrap *just that* part into a provider... you could even just inject a `Func<string, Task<SubscriberClient>>` rather than writing your own abstraction. Then use `name => SubscriberClient.CreateAsync(subscriptionName)` for the production code, and `name => Task.FromResult(fakeSubscriberClient)` in your tests.
