### ISSUE TITLE
PubSub: High TCP Connection usage

### ISSUE THREAD

**Issue by nathan-c** [googleapis/google-cloud-dotnet#5889]
I recently upgraded my dev PC (running ubuntu based pop_os) to Ryzen 5900x and found I was regularly seeing the following two exceptions while running a service that is subscribed to 36 subscriptions using SubscriberClient's and also publishing to the same number using PublisherClient's.
```
Grpc.Core.RpcException: Status(StatusCode="Unavailable", Detail="failed to connect to all addresses", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1611699451.269672651","description":"Failed to pick subchannel","file":"/var/local/git/grpc/src/core/ext/filters/client_channel/client_channel.cc","file_line":4090,"referenced_errors":[{"created":"@1611699451.269671371","description":"failed to connect to all addresses","file":"/var/local/git/grpc/src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":394,"grpc_status":14}]}")
```
```
Grpc.Core.RpcException: Status(StatusCode="DeadlineExceeded", Detail="Deadline Exceeded", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1611699451.222505294","description":"Deadline Exceeded","file":"/var/local/git/grpc/src/core/ext/filters/deadline/deadline_filter.cc","file_line":69,"grpc_status":4}")
```
We maintain a single instance of PublisherClient per topic.

After some debugging, I noticed that my process was holding over 900 TCP connections open and so after manually setting the client count on creation to 1 for both Subscriber and Publisher I found that all of these exceptions went away, and my process now holds a fewer TCP connections open. The overall throughput of my service does not seem greatly diminished (although I will need to run more tests to check this). I was under the assumption that gRPC should multiplex connections to the same host, but, looking through the [code](https://github.com/googleapis/google-cloud-dotnet/blame/cf77dacdc306fc4eaff0ad6eb3ab47eaf34ef748/apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/PublisherClient.cs#L241) I can see that it specifically prevents this, whilst also creating a channel per CPU core for both publishers and subscribers. 

Should I be worried that I was seeing the above exceptions when using the default settings? 
Do you have any recommendations to avoid/diagnose these sorts of problems quickly?
Do you have any information on why the code avoids channel multiplexing?

**Comment by chrisdunelm** [comment]
Thanks for reporting this, and I agree that this is not ideal - using default parameters should generally not cause errors like this.
Setting `ClientCount` to `1` is indeed the most appropriate way of solving this.

These `PublisherClient` and `SubscriberClient` classes are optimized for high-throughput scenarios, and defaults were chosen with this in mind.
The code avoids multiplexing over a single channel because a channel is bandwidth limited to about 150MBytes/s (due to server-side implementation constraints if I remember correctly), which would cause a bottleneck in high throughput clients.
The decision to scale channels by CPU count is a pragmatic choice to approximately scale maximum throughput performance by potential machine workload - we do not want any performance bottlenecks caused by our choice of defaults.

I would guess that 36 publisher and subscribe clients is more than most people use, and a Ryzen5900x has more cores than most. Which is why you're seeing this and others don't.
I'm not sure there's much we could do here, except possibly limit the default `ClientCount` to reasonable number e.g. 10 - however this could introduce performance limitations to users would rely on the current default, so we'd be loath to change this now.

**Comment by nathan-c** [comment]
Thanks for the detailed explanation. I agree, changing default behaviour that users may be depending on is usually a bad idea. If it is a server-side bandwidth cap, I wonder if it is possible to use network link speed to scale client counts? I suppose it might also be possible to add some scaling logic to add clients as throughput becomes throttled but I realise this would add a fair bit of complexity to the clients. 

I realise my dev use case is probably a bit out of the ordinary, and in production we run many smaller services in separate containers with constrained CPU and only a handful of subscriptions per container so we are far less likely to have this issue. For dev purposes we run all our services in one process to make debugging a little easier.

Perhaps something like your explanation above could be added to the docs so that devs can make an informed decision based on their throughput requirements?

**Comment by jskeet** [comment]
@nathan-c: That's good feedback, thanks. Chris, let's chat about who gets to write those docs, and we can get them ready for the next release.
