### ISSUE TITLE
Skip the CommitStats integration tests against the emulator

### ISSUE THREAD

**Issue by skuruppu** [googleapis/google-cloud-dotnet#5948]
Not sure why it wasn't picked up in #5506 presubmits but the CommitStats integration test is failing against the emulator. We need to skip it until the support is added to the emulator.

**Comment by skuruppu** [comment]
@olavloite if you could please take this on, that would be great. It is apparently blocking the emulator release.

**Comment by skuruppu** [comment]
For some reason I can't assign this to anyone other than myself so you will have to assign this to yourself @olavloite.

**Comment by olavloite** [comment]
> Not sure why it wasn't picked up in #5506 presubmits but the CommitStats integration test is failing against the emulator. We need to skip it until the support is added to the emulator.

I'll look into it right away. The reason that it wasn't picked up by the presubmits, is that as far as I know we are not running any of the integration tests against the emulator during presubmits for the C# client. They are only executed against a real Cloud Spanner instance.

**Comment by amanda-tarafa** [comment]
> The reason that it wasn't picked up by the presubmits, is that as far as I know we are not running any of the integration tests against the emulator during presubmits for the C# client. They are only executed against a real Cloud Spanner instance.

On presubmits we don't run integration tests against a real instance. I think we run Spanner integration tests against the emulator if the PR makes changes to Spanner libraries, #5480 actually failed against the emulator but #5506 didn't.  
Also, CI has been green since #5506 was merged and I believe that on CI we run the tests against the emulator always. So something else is going on, either the emulator version we are using does support the feature or the tests are not being even run against the emulator or the test is wrong (which doesn't seem to be the case).  
I'll take a look at our CI scripts now to confirm that we are really running the tests against the emulator.

**Comment by amanda-tarafa** [comment]
Part of the mistery solved, we moved from Travis to GitHub Actions in between #5480 and #5506 and we accidentally dropped running the tests against the emulator when there were changes in Spanner. I'm adding that back in now. Sorry!

**Comment by skuruppu** [comment]
Oh nice work figuring out the root cause. I didn't know that we had moved to GH Actions.

**Comment by amanda-tarafa** [comment]
And as far as I can see we have never ran the integration tests against the emulator on our nightly CI run, so that's all mysteries solved.
