### ISSUE TITLE
GetOrCreateDataset throws 'duplicate' GoogleApiException

### ISSUE THREAD

**Issue by guypld** [googleapis/google-cloud-dotnet#6902]
Hi,

I've found that when [GetOrCreateDataset ](https://github.com/googleapis/google-cloud-dotnet/blob/13ed74b0e70f5b9932c9f679a3378493586c2fcc/apis/Google.Cloud.BigQuery.V2/Google.Cloud.BigQuery.V2/BigQueryClientImpl.DatasetCrud.cs#L95) is being called simultaneously with the same dataset name (for example after a deployment of multiple instances) I can get the following exception:

`The service bigquery has thrown an exception: Google.GoogleApiException: Google.Apis.Requests.RequestError
Already Exists: Dataset proj-xxx:dataset-yyy [409]
Errors [
     Message[Already Exists: Dataset proj-xxx:dataset-yyy] Location[ - ] Reason[duplicate] Domain[global]`

According to the implementation this is happening because **GetDataset** throws an exception (ds not exist) and then **CreateDataset** is being called and throws 'duplication' error.

I'll let you decide whether its a bug or a feature or neither, but when I call a method that has **GetOrCreate** prefix I don't expect to get duplication error.

My quick solution is of course to implement a **SafeGetOrCreateDataset** method, but I don't like this solution.

Thanks for your time.

**Comment by jskeet** [comment]
I'll have a look at this tomorrow.

**Comment by jskeet** [comment]
Right - my proposal is that instead of "Try Get, then Create if it's not found" we move to "Try Get, then try Create if it's not found, then try Get again if that ended up with a duplication error". That should handle the "multiple concurrent GetOrCreate calls" scenario with no problems, but I *don't* propose to try to handle "multiple concurrent GetOrCreate and Delete calls" - in other words, if the final Get call fails, I won't make it go into a retry loop.

I expect to implement this today or tomorrow - and I'll do it across all similar methods. (I believe we have dataset and table; I'm not sure what else.)

**Comment by guypld** [comment]
I agree, thanks!

**Comment by jskeet** [comment]
I've started working on this, and created an integration test for it... but it gets slightly tricky if you've got a *lot* of contention - because you'll end up running out of quota for the dataset if there are more than 5 insert operations for the same dataset within 10 seconds.

Unfortunately it's relatively tricky to check whether a 403 error is actually due to quota (in which case retrying the get operation is probably appropriate) or a permissions error (in which case failing immediately is probably better).

Any thoughts? Does your use case require more than 5 GetOrCreate requests in a very short space of time? (Of course once the dataset has actually been created, it will start working due to the first Get working...)

**Comment by guypld** [comment]
Yes I understand, its a tricky thing.

My intent was to ensure dataset existence, specifically I call GetOrCreateDataset only once per instance (on initialization) and currently I have only 2 instances.
If I knew there's a quota for these kind of operations I would probably use a different logic here.

As you wrote - "Try Get, then try Create if it's not found, then try Get again if that ended up with a duplication error" is the simplest and the correct answer here, but 403 errors is indeed a nightmare.

Unfortunately I can't find a good and clean solution here, at least lets just catch the duplication error.

**Comment by jskeet** [comment]
@guypld: This is fixed in version 2.3.0 - but *without* trying to solve the quota issue. It sounds like that won't be an issue for you, so hopefully you can just update to 2.3.0.

**Comment by guypld** [comment]
Thanks for the quick response!

After I though about it, the main issue here is that I assumed that GetOrCreate method should be an atomic transaction (same as GetOrAdd in dictionaries), but its impossible to have atomicity while working with BigQuery.

**Comment by jskeet** [comment]
Yes, unfortunately there's nothing in the API to do this atomically - the GetOrCreate methods are effectively convenience methods to work around that. I think they're still better with the fix present though.
