### ISSUE TITLE
Create table with RangePartitioning

### ISSUE THREAD

**Issue by saideldah** [googleapis/google-cloud-dotnet#6970]
Hello,

I am trying to create a table using the .net API, however, I need to create the table with RangePartitioning and I found no documentation for this case.
can someone help me with this, please?

Thank you!

**Comment by jskeet** [comment]
Which API do you mean? (This repo covers a *lot* of APIs.) I'm afraid the maintainers of this repository don't know details of all the APIs, so we may not be able to help you anyway, but it would be a start. If you could clarify what makes you think you *need* range partitioning, that would help too. (Whatever document is telling you that may help us to help you.)

**Comment by saideldah** [comment]
Hi @jskeet,
Thank you for your reply so basically, I have a use case that requires me to create a table using the code if I don't have it.
However, this table should be partitioned with an integer-range partitioned field.

something similar to the java example in this [documentation](https://cloud.google.com/bigquery/docs/creating-partitioned-tables#create_an_integer-range_partitioned_table):

I was trying the following but I found that CreateTableOptions does not support the integer-range partitioned
```
var createTableOptions = new CreateTableOptions()
                {
                    TimePartitioning = partitioningOptions
                };

dataset.GetOrCreateTableAsync(
                    tableName,
                    bqMapper.BigQuerySchema,
                    createOptions: createTableOptions);
```

after searching and trying many times I found that we have `RangePartitioning` class in the `Google.Apis.Bigquery.v2` namespace but not documentation!

**Comment by amanda-tarafa** [comment]
Hi @saideldah several parts to your question:

- If you can set a `TimePartioning` on `CreateTableOptions` then you are using a very (very) old library version. You'll want to update to a newer version since the feature you are looking to use is somewhat new and it is not supported by old versions of the library. I'll advise you to update to our [latest version](https://www.nuget.org/packages/Google.Cloud.BigQuery.V2/), not just to use this feature, but also because of other improvements, bug fixes, features, etc.
- For creating a table, you now create the `Table` instance and configure that as you need. Your code would look something like this:

```csharp
Table table = new Table
{
    Schema = bqMapper.BigQuerySchema,
    RangePartitioning = new RangePartitioning
    {
        Field = "age",
        Range = new RangePartitioning.RangeData
        {
            Start = 0,
            End = 120,
            Interval = 20,
        }
    }
};

await dataset.GetOrCreateTableAsync(tableName, table);
```

- Please notice that this feature is marked as `Experimental` on the [BigQuery API reference docs](https://cloud.google.com/bigquery/docs/reference/rest/v2/tables#rangepartitioning) and as `Trusted Tester` on the [Google.Apis.Bigquery.v2 library reference docs](https://googleapis.dev/dotnet/Google.Apis.Bigquery.v2/latest/api/Google.Apis.Bigquery.v2.Data.RangePartitioning.html#Google_Apis_Bigquery_v2_Data_RangePartitioning_Field). For finding out exactly what that means and what implications it may have for you, use one of the support channels listed on the [BigQuery documentation](https://cloud.google.com/bigquery/docs/support).

**Comment by saideldah** [comment]
@amanda-tarafa 
Thank you very much!
you have saved my day
