### ISSUE TITLE
Unclear how to clear buffer from PubSub ApiClients

### ISSUE THREAD

**Issue by pbiggar** [googleapis/google-cloud-dotnet#8477]
When reading the docs for version 2.9.0 of the PubSub .NET documentation, it wasn't clear how to flush the buffers so that my service could be safely shut down.

I eventually found what I believe is the right doc, but even this isn't super clear https://cloud.google.com/dotnet/docs/reference/help/cleanup#grpc-based-apis-and-channels

I'd suggest adding `Shutdown` or `Flush` methods to `PublisherServiceApiClient` and `SubscriberServiceApiClient`, similar to what's on `PublisherClient` and `SubscriberClient`. That would be much clearer.

**Comment by jskeet** [comment]
There aren't any buffers in `PublisherServiceApiClient` or `SubscriberServiceApiClient`. They're just stateless RPC clients - unlike `PublisherClient` and `SubscriberClient`. The only thing to shut down is the network connection (which varies based on how the client was constructed), and unless you have a currently-active RPC, there's nothing to be careful of there. (As it happens I'll be rewriting that page soon anyway, due to the changes in the next major version, but there still won't be any buffers to flush.)

Does that alleviate your concerns?

**Comment by pbiggar** [comment]
Yes! Much appreciate, thanks!
