### ISSUE TITLE
Examples in c# for Google.Cloud.BigQuery.Storage.V1

### ISSUE THREAD

**Issue by rocklan** [googleapis/google-cloud-dotnet#8815]
Could we have a few examples on how to read and write data to bigquery in c# using the new `Google.Cloud.BigQuery.Storage.V1` package? As far as I can tell there's [one example](https://cloud.google.com/dotnet/docs/reference/Google.Cloud.BigQuery.Storage.V1/latest/Google.Cloud.BigQuery.Storage.V1.BigQueryWriteClient) and this example inserts nothing, I think, it's very hard to tell. Searching for information on `BigQueryWriteClient`  and  `AppendRowsRequest` didn't yield much results. It's also not clear if I need to listen to the response Stream. Do I have to? 

The [other](https://codelabs.developers.google.com/codelabs/cloud-bigquery-csharp#9) [examples](https://github.com/googleapis/google-cloud-dotnet/blob/main/apis/Google.Cloud.BigQuery.V2/Google.Cloud.BigQuery.V2.Snippets/BigQueryClientSnippets.cs) out there all use the old `Google.Cloud.BigQuery.V2` package, if they could be updated for the new package that would be great.

**Comment by Rishabh-V** [comment]
Hi @rocklan,

Please see if [this sample](https://cloud.google.com/bigquery/docs/write-api-batch#c) based on `Google.Cloud.BigQuery.Storage.V1` helps?

**Comment by jskeet** [comment]
Just to provide a little more information... Rishabh has pointed to a fairly comprehensive sample for the storage-specific library.

We won't be updating the samples you referred to to use the storage-specific library, because they're explicitly intended to be samples for Google.Cloud.BigQuery.V2. While obviously we fully support folks using the storage-specific library, the more general-purpose library isn't going away, and still needs samples. There are *more* samples for that than for other libraries, partly because it's a hand-written abstraction over the underlying REST-based library.

I'll close this now as I don't think there are any changes to make within this repo; the BigQuery product team may introduce more cross-language samples for the Storage API over time, of course.
