### ISSUE TITLE
Add Interface for SpannerConnection

### ISSUE THREAD

**Issue by Steven-Harris** [googleapis/google-cloud-dotnet#8868]
**Is your feature request related to a problem? Please describe.**
I'd like to have an interface SpannerConnection. Currently it's a sealed class, which means mocking tools like moq can't mock them.

 **Describe the solution you'd like**
Add an interface

 **Describe alternatives you've considered**
I have tried making a wrapper class to abstract the SpannerConnection class, but was unsuccessful.

**Comment by jskeet** [comment]
We've talked about this, and we'd really like to *not* do this, for a few reasons.

Firstly, if we put everything in `SpannerConnection` into an interface, then we end up with versioning problems if we ever add a new member: adding a new interface member is a breaking change.

Secondly, it wouldn't just be `SpannerConnection` you'd want to mock - for example, the `SpannerConnection` class has methods returning `SpannerCommand`, and `SpannerCommand` itself expects a `SpannerConnection`. Likewise there's `SpannerTransaction` which doesn't even have any public constructors, so you wouldn't be able to mock any methods returning a `SpannerTransaction`. We could add interfaces to all of these, but then we'd need breaking changes (or separate interface methods) to make everything accept/return the interfaces.

In the bigger picture, I tend to find that mocking is a brittle approach to testability for database-oriented operations.

If you really want to mock the individual operations, I'd suggest creating a wrapper class and an interface around it - that way your requirements don't need to affect other users of the library (and you only need to include the members that your application needs, which simplifies things significantly). You say you tried this but were unsuccessful - if you provide more information about what you tried and what went wrong, we can potentially help you.

However, I'd personally recommend against using mocking at this low level anyway. Instead, work out a higher level abstraction that you can use throughout your app, as (ideally) the only place that really needs to know about Spanner in detail. You can then create a test double of that abstraction (whether through mocking or another kind of test double - I tend to use hand-written fakes) and write comprehensive integration tests for the implementation so that you can trust that piece of code. (I'd recommend full application integration tests as well of course, but they can probably be less thorough.) Note that you can integrate with the emulator as another approach to integration tests, too.

I'll leave this issue open for the moment so that we can help you with the wrapper class approach if you want to go down that route, but I'll close #8869 as we don't intend to merge that.

**Comment by Steven-Harris** [comment]
Thank you for your consideration!  

# Workaround
I was able to create an adapter class that seems to be working well for me now. I hadn't designing the adapter right yesterday and It dawned on me later there was a simple solution. 😅
```cs
public class SpannerConnectionAdapter<T>
{
    private readonly SpannerConnection connection;

    public SpannerConnectionAdapter(SpannerConnection connection)
    {
        this.connection = connection;
    }

    public async Task<T?> ExecuteSql(string sql, CancellationToken cancellationToken)
    {
        await this.connection.OpenAsync(cancellationToken);

        await using SpannerCommand cmd = this.connection.CreateSelectCommand(sql);

        await using SpannerDataReader reader = await cmd.ExecuteReaderAsync(cancellationToken);

        return await reader.ToEntity<T>();
    }

    public async Task ExecuteNonQuerySql(string sql, CancellationToken cancellationToken)
    {
        await this.connection.OpenAsync(cancellationToken);

        await using SpannerCommand? cmd = this.connection.CreateDmlCommand(sql);
        cmd.Priority = Priority.Low;

        var rowCount = await cmd.ExecuteNonQueryAsync(cancellationToken);
        if (rowCount < 0)
        {
            throw new Exception($"{nameof(this.ExecuteNonQuerySql)} was unsuccessful executing the provided sql");
        }
    }
}
```
# Use Case
I'd be using it when testing repositories that use the spanner connection. Your right, I wouldn't want to go to any low level test. I just want to provide a fake instance of spanner in my test to test the repository. However, because the class is `sealed` I can't extend the base class to fake it. 

```
public class FakeSpannerConnection : SpannerConnection { } 
// error FakeSpannerConnection can not derive from sealed type SpannerConnection
```

# Responses
I am little confused why you think you would need to put interfaces on the `Spanner*` return objects. I don't see why that would be needed. Moq can easily mock an Interface that has class objects in them. I'm also confused why you say mocking is brittle. Fakes are also valid to use, but to each their own.

# Plead
I hope you and your team reconsider. Not having an interface violates the "Interface Segregation" and "Liskov substitution" principles of S.O.L.I.D design practices. It would simplify the coded need to test, as now everyone that has a class that uses Spanner has to write an adapter class. It would also help dependency injection and unit testing best practices. I would argue too, modern ide's can update the interface for you so it's not a huge deal to maintainability. Lastly, from a library perspective it
s a good thing to have a clear contract for your code so your consumers can easily implement it. 

No hard feelings either way.

**Comment by jskeet** [comment]
I'm afraid I'm still not convinced. Answers to a few of your points:

> I am little confused why you think you would need to put interfaces on the `Spanner*` return objects. I don't see why that would be needed. Moq can easily mock an Interface that has class objects in them.

Yes, but what would your test look like? For example, consider these lines of code in your adapter:

```csharp
await using SpannerCommand cmd = this.connection.CreateSelectCommand(sql);
await using SpannerDataReader reader = await cmd.ExecuteReaderAsync(cancellationToken);
```

Suppose `connection` was an `ISpannerConnection` instead of just `SpannerConnection`. How would you set up the mock - what would you make it return from `CreateSelectCommand` method? A "real" `SpannerCommand` with no connection? That's going to fail at the next line. Presumably you want to provide some results for `ExecuteReaderAsync`, so you'd presumably *actually* want to mock the `SpannerCommand`. Even if you could do that, you'd have to return a `SpannerDataReader` from `SpannerCommand`, and there are no public constructors to `SpannerDataReader`. This is why I'm saying that *just* mocking `SpannerConnection` wouldn't actually help you much.

> I'm also confused why you say mocking is brittle.

In my experience, tests using mocking *tend* to end up describing the expected implementation rather than describing the expected result. In many situations there can be multiple ways of getting to the expected result - and if it becomes useful to change the implementation from one of those ways to another, tests using mocks tend (again, in my experience) to require more changes than tests that use other kinds of test doubles.

Mocks are great when you really, really want interaction testing - when your requirements are absolutely precise in terms of how you interact with your dependencies (and sometimes in what order, e.g. doing authorization before making any data changes) but I strongly believe that trying to mock this sort of interaction would be really painful. (We have some mock tests within this code base, out of necessity because we do want to validate the precise requests we're making - they're not fun.)

> Not having an interface violates the "Interface Segregation" and "Liskov substitution" principles of S.O.L.I.D design practices.

I'd argue that *adding* an interface would violate Interface Segregation. `SpannerConnection` is a bit of a "kitchen sink" class - and that's the nature of database access classes that provide a wide range of very specific capabilities. However, if lots of your codebase depends on `SpannerConnection`, that's a lot of code depending on a class which it will only use a small part of.

Introducing your own repository classes (or whatever abstractions are appropriate) is the way to *provide* interface segregation.  Most of your code only needs to depend on the abstractions provided at the core, and those abstractions can have whatever interfaces you want. Again, I'd strongly advise you to rely heavily on *integration* testing rather than *unit* testing for the core classes - because that will tell you whether you're *actually* interacting with Spanner in a way that works. By thoroughly testing those core abstractions with integration tests, you can use unit tests for the rest of the application that depends on the core abstractions. (Note that the core abstractions will vary by customer, which is why we don't provide that sort of thing ourselves.)

As for Liskov Substitution: I don't see how it can violate the principle, given that the principle only applies when there *are* subtypes. You'd have to talk about whether `SpannerConnection` is a suitable subtype of `DbConnection` - and in this case, I believe it is. Liskov Substitution doesn't require that subtypes actually exist - it just says that where they *do* exist, they shouldn't behave in a surprising way.

> I would argue too, modern ide's can update the interface for you so it's not a huge deal to maintainability. 

I think you've misunderstood my maintenance objection. Keeping the interface up-to-date is definitely not a *mechanical* problem, whether that's done via an IDE or manually, checked via unit tests etc. But *adding a member to an interface is a breaking change*. That means whenever we wanted to add a new member to `SpannerConnection`, we'd need to decide between options of creating a new major version (has cost for all consumers, who should check whether it will break them before adopting) or letting the interface and the class get out of sync (reduces the benefit of having an interface in the first place).

I'm going to close this issue now as it sounds like you've got a workaround. I suspect further discussion probably wouldn't help in terms of either of us persuading the other.
