### ISSUE TITLE
Firestore: Expose GetDocument endpoint for querying a single document

### ISSUE THREAD

**Issue by alex-namely** [googleapis/google-cloud-dotnet#9060]
Hi, regarding the Firestore Client, I am curious to know if there is any way to get a single document using [GetDocument](https://firebase.google.com/docs/firestore/reference/rpc/google.firestore.v1#google.firestore.v1.Firestore.GetDocument) rpc endpoint.

Currently from what I can see the library always use [BatchGetDocuments](https://firebase.google.com/docs/firestore/reference/rpc/google.firestore.v1#google.firestore.v1.Firestore.BatchGetDocuments) endpoint.

Reference in source codes is [here](https://github.com/googleapis/google-cloud-dotnet/blob/d1fcb949ba6896096a6467f0581cf9015dbe8c75/apis/Google.Cloud.Firestore/Google.Cloud.Firestore/FirestoreDb.cs#L286)

Google.Cloud.Firestore .NET trace
![f2](https://user-images.githubusercontent.com/41734618/187690616-356a3a5e-571e-4bd6-a894-df7d25ec7957.png)

Python SDK trace
![f1](https://user-images.githubusercontent.com/41734618/187690577-c4b7033e-62d8-46fe-bdb7-37292f04dd6a.png)

**Comment by jskeet** [comment]
Well you *could* call the RPC directly yourself, but no, the Google.Cloud.Firestore library always uses BatchGetDocuments, to simplify the implementation. (Given that we need to use it to fetch multiple documents, it's simple to use it for the single document case too.)

Is there any particular reason you want to avoid BatchGetDocuments?

**Comment by alex-namely** [comment]
Hi @jskeet 

Main reason why I am asking is a hope that _GetDocument_ endpoint might be faster than _BatchGetDocuments_. 

Another minor issue is that GetDocument throws 404 when the document is not found where BatchGetDocuments returns an empty collection.

Using underlying client requires manually building document path and this is not easy and clean.

**Comment by jskeet** [comment]
> Main reason why I am asking is a hope that GetDocument endpoint might be faster than BatchGetDocuments.

I definitely don't want to introduce more complex code baths just based on a *hope*.

If you're willing to do performance testing to prove that it *is* significantly faster, then we could look into using GetDocument.

> Another minor issue is that GetDocument throws 404 when the document is not found where BatchGetDocuments returns an empty collection.

Well we can't change what the layered API does for that case anyway. That would be a breaking change. The use of GetDocument instead of BatchGetDocuments would have to be *just* an implementation detail. Additionally, if we need to catch an exception if the document doesn't exist, that could have a performance impact on its own - it may end up being faster than the batch fetch when it *does* exist, but slower when it doesn't. We'd need to balance those competing concerns.

**Comment by jskeet** [comment]
Closing due to lack of further information. @alex-namely if you want to add more information later, e.g. having done some benchmarking, we can reopen the issue at that point.
