### ISSUE TITLE
Fails to parse create_time with hour specification

### ISSUE THREAD

**Issue by greg-signi** [googleapis/google-cloud-dotnet#9297]
Throws the following error: 

> Status(StatusCode="InvalidArgument", Detail="syntax error at line 1, column 27, token ':'")

Stack trace:

Grpc.Core.RpcException : Status(StatusCode="InvalidArgument", Detail="syntax error at line 1, column 27, token ':'")
[xUnit.net 00:00:34.61]       Stack Trace:
[xUnit.net 00:00:34.61]            at Google.Api.Gax.Grpc.ApiCallRetryExtensions.<>c__DisplayClass0_0`2.<<WithRetry>b__0>d.MoveNext()
[xUnit.net 00:00:34.61]         --- End of stack trace from previous location ---
[xUnit.net 00:00:34.61]            at Google.Api.Gax.Grpc.ResponseAsyncEnumerable`3.ResponseAsyncEnumerator.MoveNextAsync()
[xUnit.net 00:00:34.61]            at System.Threading.Tasks.Parallel.<>c__54`1.<<ForEachAsync>b__54_0>d.MoveNext()

I followed the documentation https://cloud.google.com/secret-manager/docs/filtering

var listSecretVersionsRequest = new ListSecretVersionsRequest
  {
      Filter = $"create_time<={minCreateDate:yyyy-MM-ddTHH:mm:ssZ} AND STATE!=DESTROYED",
      ParentAsSecretName = SecretName.FromProjectSecret(_projectName.ProjectId, secretId),
      PageSize = MaxItemsPerPage,
  };

Results in `Filter=create_time<=2022-11-09T11:40:16Z AND STATE!=DESTROYED`

This is in agreement with the format [RFC 3399](https://tools.ietf.org/html/rfc3339)

**This won't happen if I dont specify the hours,minutes,seconds**

#### Environment details

  - OS: Windows
  - .NET version: 4.8.04084
  - Package name and version: Google.Cloud.SecretManager.V1 2.0.0

#### Steps to reproduce

  1. Create a ListSecretVersionsRequest with Filter with a time parameter specifying hours, minutes, seconds
  2. Call SecretManagerServiceClient.ListSecretVersionsAsync

Thanks!

**Comment by jskeet** [comment]
This isn't an issue with the .NET client library - it's an issue with the server-side API. You can observe the same behavior by executing the method interactively (with ListSecrets rather than ListSecretVersions for simplicity) here: https://cloud.google.com/secret-manager/docs/reference/rest/v1/projects.secrets/list

With brief experimentation, it *looks* like removing the colons between the hours, minutes and seconds works (so 2022-11-09T114016Z) but that's just with a very quick test.

As this isn't an issue with the client library itself, I'll close this issue - but if you wish to pursue it further, please follow one of the [SecretManager support routes](https://cloud.google.com/secret-manager/docs/getting-support) - e.g. [filing an issue on the IssueTracker](https://issuetracker.google.com/issues/new?component=784854).

**Comment by greg-signi** [comment]
Didn't seem to work for me Detail="The value '2022-11-09t122050z' is of incorrect type."
Thanks, I'll file the issue.

**Comment by greg-signi** [comment]
Yes, I sent as `Filter=create_time<=2022-11-09T114016Z`.

But the error that comes back appears to have lowercased both T and Z. Some formatting error I would assume since it's not a valid date.

**Comment by jskeet** [comment]
Okay - thanks for the update. I won't pursue this any further, but it's good to know of the issue in case other customers encounter it.

I see the issue you've filed - thanks for that. For the sake of anyone else reading this issue later, see https://issuetracker.google.com/issues/258277871
