### ISSUE TITLE
Parameter validation failed for session Google.Apis.Dialogflow.v3

### ISSUE THREAD

**Issue by kristinmc0215** [googleapis/google-cloud-dotnet#9346]
Hi - I'm trying to update my code from v2 to v3, and I'm having problems with the attached issue - trying to send a request to CX via the .NET nuget package for v3 dialogflow. Everything is working for the ES/v2 version, but for some reason I can't figure out why this isn't working.

**Comment by kristinmc0215** [comment]
Can't seem to attach an image, so here is the actual error message:

Google.GoogleApiException
  HResult=0x80131500
  Message=Parameter validation failed for "session" : The value did not match the regular expression ^projects/[^/]+/locations/[^/]+/agents/[^/]+/sessions/[^/]+$
  Source=Google.Apis
  StackTrace:
   at Google.Apis.Requests.ClientServiceRequest`1.AddParameters(RequestBuilder requestBuilder, ParameterCollection inputParameters)
   at Google.Apis.Requests.ClientServiceRequest`1.CreateBuilder()
   at Google.Apis.Requests.ClientServiceRequest`1.CreateRequest(Nullable`1 overrideGZipEnabled)
   at Google.Apis.Requests.ClientServiceRequest`1.<ExecuteUnparsedAsync>d__34.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Google.Apis.Requests.ClientServiceRequest`1.Execute()

**Comment by jskeet** [comment]
We don't know what value you're providing for `session` - or even which method you're trying to call. I suspect this isn't a client library issue though; I suspect the resource name string for the session resource is just slightly different in Dialogflow v3.

I'd also note that the client library you're using is of the older kind - in general I'd recommend moving to [Google.Cloud.Dialogflow.Cx.V3](https://www.nuget.org/packages/Google.Cloud.Dialogflow.Cx.V3). Although if you're using the old version of Dialogflow.v2 as well, it will mean more changes to your code.
Moving to the more modern library won't fix the problem though - you really need to use the resource name format that Dialogflow wants.

**Comment by kristinmc0215** [comment]
Thanks jskeet, after I posted this I did figure out that I had the wrong resource name string. I'm currently trying to upgrade my code from Google.Apis.Dialogflow.v2 to Google.Apis.Dialogflow.v3. Is that one in the same with Google.Cloud.Dialogflow.Cx.v3? Or do I need to make additional changes to move to Google.Cloud?

**Comment by jskeet** [comment]
Google.Apis.Dialogflow.v3 and Google.Cloud.Dialogflow.Cx.V3 are different libraries for the same API. The first uses JSON and HTTP/1.1, and is based on a now-pretty-old code generator. The second uses gRPC with protobuf over HTTP/2.0, and is based on a more modern generator.

In general, we think you'll have a better time with the latter library - and the generator for that is the one where most ongoing work happens. The old-style library should still work fine, and if you have reasons to use it then that's absolutely fine - but if you're happy to put in a bit of work to migrate to the Google.Cloud.Dialogflow.Cx.V3 library, I think you'll find it pays off in the long run, in terms of usability.

I'll close this issue now, as it sounds like your problem is resolved.
