### ISSUE TITLE
Google.Cloud.Run.V2 : Services.GetService not working

### ISSUE THREAD

**Issue by christopheblin** [googleapis/google-cloud-dotnet#9356]
I'm trying to perform what I think was super-simple :  retrieving the public Uri of the cloud run from inside my app

```
        var client = await Google.Cloud.Run.V2.ServicesClient.CreateAsync();
        var res = await client.GetServiceAsync(Google.Cloud.Run.V2.ServiceName.FromProjectLocationService(_options.ProjectId, _options.Location, _options.ServiceName));
        _logger.LogInformation("CloudRun Uri is {}", res.Uri);
```

```
 at Redacted.RetrieveCloudRunUrl() in Redacted.cs:line 38
--- End of stack trace from previous location ---
 at Google.Api.Gax.Grpc.ApiCallRetryExtensions.<>c__DisplayClass0_0`2.<<WithRetry>b__0>d.MoveNext()
Unhandled exception. Grpc.Core.RpcException: Status(StatusCode="Unimplemented", Detail="Operation is not implemented, or supported, or enabled.")
```

When I go to the API dashboard https://console.cloud.google.com/apis/api/run.googleapis.com/metrics?project=redacted, I can see the error

![gcp_cloudrun_getservice_error2](https://user-images.githubusercontent.com/11044877/203518652-c5f8a10b-9a94-4bff-acb2-d77504c0cba9.png)

=> what is the correct way to retrieve the public uri of the running cloud run if this method is not available ?

**Comment by jskeet** [comment]
That certainly *looks* like it should work. My guess (purely based on previous similar things) is that there's an internal routing issue. I'll look into it - thanks for the report.

Could you let me know which location this was in? (That could be relevant - and I'm afraid the screenshot is too small for me to see.)

**Comment by christopheblin** [comment]
@jskeet location is eu-west1

**Comment by jskeet** [comment]
Thanks for both updates - that's really useful. I'll try to repro in the next half hour, and report back.

**Comment by jskeet** [comment]
Okay, I think it's simple - the region should be "europe-west1" rather than "eu-west1". I've got a service in "europe-west1" and I'm able to retrieve it with no problems, but if I specify the location as "eu-west1" I get the same exception as you.

It's a pretty unfortunate failure mode though - I'll raise that internally. (I suspect this isn't a Cloud-Run-specific issue - it'll take a little while to work out where to file it.)

**Comment by jskeet** [comment]
@christopheblin: Please could you confirm if this fixes your issue? If so, I'll close this GitHub issue - but pursue the failure mode internally.

**Comment by christopheblin** [comment]
@jskeet I'm not able to work on this problem right now but, with your message, I think it's pretty clear that it will work with the correct location => I close this issue and thank you very much for the timely support 👍

**Comment by christopheblin** [comment]
@jskeet just another (minor) point : calling this method will return an empty Uri if this is the first deployment of the service

This is a bit annoying to me because I try to read the Cloud Run Uri during startup of my app (in order to create pubsub push subscritptions from the code)

As a workaround, I have to deploy the service manually on a test container first (so there is an Uri assigned to the cloud run), and then I can use my own container image ...

**Comment by jskeet** [comment]
@christopheblin: I would suggest raising that via one of the [support routes for Cloud Run](https://cloud.google.com/run/docs/support) - it's not really a client library issue as such. We try to avoid getting heavily involved in API-specific feature requests or issues, as otherwise we're constantly playing a game of telephone...
