### ISSUE TITLE
use OpenTelemetry with Google Trace

### ISSUE THREAD

**Issue by christopheblin** [googleapis/google-cloud-dotnet#9656]
In my code, I am currently using builder.Services.AddGoogleDiagnosticsForAspNetCore() as documetned in https://cloud.google.com/dotnet/docs/reference/Google.Cloud.Diagnostics.AspNetCore3/latest

Now, I'd like to switch to a more generic Opentelemetry approach (like very well described with zipkin in https://craftbakery.dev/try-zipkin/)

I see that other languages should directly use Open Telemetry (https://cloud.google.com/trace/docs/setup#recommended_client_libraries)

=> is there a chance that we can already switch to Open Telemetry with Asp.NET Core ?
If yes, is there a chance to have some pointers ?

**Comment by jskeet** [comment]
Currently, no - but we're looking at this, as captured in #8366.

Assigning to @Rishabh-V to see if there's more to this issue than I can spot (as he's been looking at this) but I *suspect* it'll be best if you (@christopheblin) subscribe to #8366 and we keep that as the single source of updates for OpenTelemetry.

**Comment by Rishabh-V** [comment]
Hi @christopheblin, There is an option to use OpenTelemetry with ASP.NET Core and Google Cloud Trace. 

- Leverage the OpenTelemetry packages with ASP.NET Core as described in this [getting started guide in OpenTelemetry website](https://opentelemetry.io/docs/instrumentation/net/getting-started/). This should help set-up OpenTelemetry with your ASP.NET Core app.
- The exporter shown in the guide is a Console Exporter. To export the data to Google Cloud Trace, use the community written StackDriver exporter described [here](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/tree/main/src/OpenTelemetry.Exporter.Stackdriver)

These steps should get you started. However, we can't actually _recommend_ these packages at the moment, partly as they're third-party packages we're not responsible for, and partly because they're pre-releases.

**Comment by christopheblin** [comment]
@jskeet @Rishabh-V thanks for the detailed answers, I already follow #8366 so I'm glad it will be included there ! this is such a pleasure to work with you ❤️ 

I'll investigate the solution proposed by @Rishabh-V next week and report here

**Comment by jskeet** [comment]
Great, thanks. I'll close this issue now, so we can keep everything on the other issue.

**Comment by rajiv36** [comment]
> @jskeet @Rishabh-V thanks for the detailed answers, I already follow #8366 so I'm glad it will be included there ! this is such a pleasure to work with you ❤️
> 
> I'll investigate the solution proposed by @Rishabh-V next week and report here

Hi Christopheblin, Did you give it a try. Wondering if you evaluated it(telemetry dot net with StackDriver exporter  ) as I wanted to give it a try.

**Comment by christopheblin** [comment]
@rajiv36 no I did not dig into OpenTelemetry, in the end, I used #9948
