### ISSUE TITLE
Move to System.Text.Json instead of Newtonsoft.Json

### ISSUE THREAD

**Issue by AlexandreBossard** [googleapis/google-cloud-dotnet#9830]
.Net provides a reasonable JSON library with `System.Text.Json` for a while now. Performances aside, it does not require an external package reference, as it is provided by the framework.

Also, the reference to the JSON library is in the `Common` project. But only a few libraries actually requires it. This cause a extra dependency to be pulled for unfortunately no reason.

**Comment by jskeet** [comment]
It's not for no reason. It's for backward compatibility, due to transitive dependencies. We'd love to remove that dependency as well, but it's not as simple as you imply.

The libraries in this repo depend (via GAX) on Google.Apis.Auth for authentication. That in turn depends on Google.Apis.Core, which depends on Newtonsoft.Json. We can't change Google.Apis.Core to remove that dependency, because JSON settings are publicly exposed.

We do have a very long term plan to move the libraries in this repo (at least other than Google.Cloud.Storage.V1, Google.Cloud.BigQuery.V2 and Google.Cloud.Translation.V2) to a version of GAX that uses a new auth library - at which point the transitive dependency will be severed. But that needs a lot of work in various ways - and until then, we really can't move off Newtonsoft.Json.

**Comment by AlexandreBossard** [comment]
I see, thank you for your answer.

**Comment by jskeet** [comment]
Closing as there's nothing we can do in the short/medium term.
