### ISSUE TITLE
Consider adding a simple trace correlation mechanism to Google.Cloud.Logging.Console.

### ISSUE THREAD

**Issue by amanda-tarafa** [googleapis/google-cloud-dotnet#9948]
This would allow applications already in posession of a collected trace context to specify it on log entries so they are correlated.

Out of scope: any mechanism to create, augment, or collect trace contexts.

To provide an alternative for #9868 use case.

**Comment by christopheblin** [comment]
Hi @amanda-tarafa 

any progress on this ?

I make no progress on #9868 (still missing traces with SizedBuffer and even with NoBuffer) so maybe this lib could get me out of troubles (i.e avoid grpc calls for logs/traces that are slowing done http requests)

**Comment by amanda-tarafa** [comment]
I'm out sick, but I'll try and see what I can do as soon after I'm back. Mid to late week most likely. Sorry for the wait, we'll get there.

**Comment by amanda-tarafa** [comment]
Just a note: we are considering the options here, I'll update when I know more.

**Comment by amanda-tarafa** [comment]
Quick update, we are working on this. We have a tentive proposal that if approved, we should start implementing in the next few days.

**Comment by Rishabh-V** [comment]
We can close this once the documentation is updated with the desired level of information.

**Comment by jskeet** [comment]
Closing - the code has been released, and the docs will be published at https://cloud.google.com/dotnet/docs/reference/Google.Cloud.Logging.Console/latest in due course. (It takes a while for them to be processed.)

**Comment by christopheblin** [comment]
Hi @jskeet and @amanda-tarafa 

Sorry for the delay, we had another project in front of this one...

I've followed the documentation, it is working : I can see logs in Logs explorer and I can click on the left arrow to see all logs of the same trace

![image](https://github.com/googleapis/google-cloud-dotnet/assets/11044877/d0b89010-531e-4df4-a8c7-5eb837cb7b9b)

However, the view trace details is not working

![image](https://github.com/googleapis/google-cloud-dotnet/assets/11044877/bd6c835b-3422-4be2-b218-3944f55901fa)

Here is an example project (be aware to replace values in cloudbuild.yaml / cloudrun.yaml)

[gcp-log-trace.zip](https://github.com/googleapis/google-cloud-dotnet/files/11830416/gcp-log-trace.zip)

Given the doc https://cloud.google.com/dotnet/docs/reference/Google.Cloud.Logging.Console/latest#log-trace-correlation, I'd expect traces to work 
1. application exports log entries to Google Cloud Logging => yes because of cloud run
2. application exports traces to Google Cloud Trace.=> yes because of cloud run default
3. having trace context => yes becasuse of ASP.NET core
4. The console formatter configured with the Google Cloud Project ID => yes because of the line `builder.Logging.AddGoogleCloudConsole(options => options.TraceGoogleCloudProjectId = gcpProject);


IMHO, the point 2 is the issue : the doc says "by default Cloud run exports traces" but this is not the case I think

=> how can we diagnose this point ? should i open a new issue ?

**Comment by amanda-tarafa** [comment]
Yes please, can you create a new issue with the repro? I'll take a look as soon as I'm able.
